
// This file is generated by src/Tools/generateTemplates/templateClassPyExport.py out of the XML file
// Every change you make here gets lost in the next full rebuild!
#ifndef PART_RECTANGULARTRIMMEDSURFACEPY_H
#define PART_RECTANGULARTRIMMEDSURFACEPY_H

#include <Mod/Part/App/GeometrySurfacePy.h>
#include <Mod/Part/App/Geometry.h>
#include <string>


namespace Part
{

//===========================================================================
// RectangularTrimmedSurfacePy - Python wrapper
//===========================================================================

/** The python export class for GeomTrimmedSurface
 */
class PartExport RectangularTrimmedSurfacePy : public Part::GeometrySurfacePy
{
protected:
    ~RectangularTrimmedSurfacePy() override;

public:
    static PyTypeObject   Type;
    static PyMethodDef    Methods[];
    static PyGetSetDef    GetterSetter[];
    PyTypeObject *GetType() override {return &Type;}

public:
    RectangularTrimmedSurfacePy(GeomTrimmedSurface *pcObject, PyTypeObject *T = &Type);
    static PyObject *PyMake(PyTypeObject *, PyObject *, PyObject *);
    int PyInit(PyObject* args, PyObject*k) override;


    using PointerType = GeomTrimmedSurface*;

    PyObject *_repr() override;        // the representation
    std::string representation() const;

    /** @name callbacks and implementers for the python object methods */
    //@{
    /// callback for the setTrim() method
    static PyObject * staticCallback_setTrim (PyObject *self, PyObject *args);
    /// implementer for the setTrim() method
    PyObject*  setTrim(PyObject *args);
    //@}


    /** @name callbacks and implementers for the python object attributes */
    //@{
    ///getter callback for the BasisSurface attribute
    static PyObject * staticCallback_getBasisSurface (PyObject *self, void *closure);
    /// getter for the BasisSurface attribute
    Py::Object getBasisSurface() const;
    /// setter callback for the BasisSurface attribute
    static int staticCallback_setBasisSurface (PyObject *self, PyObject *value, void *closure);
    // no setter method,  BasisSurface is read only!
    //@}

    /// getter method for special attributes (e.g. dynamic ones)
    PyObject *getCustomAttributes(const char* attr) const;
    /// setter for special attributes (e.g. dynamic ones)
    /// Output: Success=1, Failure=-1, Ignore=0
    int setCustomAttributes(const char* attr, PyObject *obj);
    PyObject *_getattr(const char *attr) override;              // __getattr__ function
    int _setattr(const char *attr, PyObject *value) override;   // __setattr__ function

    /// getter for the object handled by this class
    GeomTrimmedSurface *getGeomTrimmedSurfacePtr() const;

};

}  //namespace Part

#endif  // PART_RECTANGULARTRIMMEDSURFACEPY_H


