.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH FREECAD 1 "July  25, 2007" freecad "Linux User's Manual"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
freecad \- An extensible Open Source CAx program for Unix/X11
.SH SYNOPSIS
.B freecad
.RI [ options ] " files"
.br
.B freecadcmd
.RI [ options ] " files"
.SH DESCRIPTION
.B FreeCAD
is an Open Source CAx RAD based on OpenCasCade, Qt and Python. It features 
some key concepts like macro recording, workbenches, ability to run as a 
server and dynamically loadable application extensions and it is designed 
to be platform independent.
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH USAGE
\fBfreecad\fR starts with a GUI while \fBfreecadcmd\fR is only a pure command line version that starts a Python interpreter.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of the options supported by \fBfreecad\fR is included below.
.SS "Generic options"
.TP
\fB\-h, \-\-help\fR
Show summary of options.
.TP
\fB\-v, \-\-version\fR
Show version of program.
.TP
\fB\-c, \-\-console\fR
Start in console mode.
.TP
\fB\-\-response\-file\fR \fIarg\fR
Can be specified with '@name', too.

.SS "Configuration"
.TP
\fB\-l, \-\-write\-log\fR
Write a log file.
.TP
\fB\-t, \-\-run\-test\fR \fIarg\fR
Test level.
.TP
\fB\-M, \-\-module\-path\fR \fIarg\fR
Additional module path.
.TP
\fB\-P, \-\-python\-path\fR \fIarg\fR
Additional Python path.
.SH SEE ALSO
To get more information about \fBFreeCAD\fR, please visit \fIhttp://juergen\-riegel.net/FreeCAD/Docu/index.php/Main_Page\fR
.SH BUGS
To report a bug, please visit \fIhttp://free-cad.sf.net/\fR
.SH AUTHOR
This manual page was written by Werner Mayer.
