
// This file is generated by src/Tools/generateTemplates/templateClassPyExport.py out of the XML file
// Every change you make here gets lost in the next full rebuild!
#ifndef SURFACE_BLENDCURVEPY_H
#define SURFACE_BLENDCURVEPY_H

#include <Base/BaseClassPy.h>
#include <Mod/Surface/App/Blending/BlendCurve.h>
#include <string>


namespace Surface
{

//===========================================================================
// BlendCurvePy - Python wrapper
//===========================================================================

/** The python export class for BlendCurve
 */
class SurfaceExport BlendCurvePy : public Base::PyObjectBase
{
protected:
    ~BlendCurvePy() override;

public:
    static PyTypeObject   Type;
    static PyMethodDef    Methods[];
    static PyGetSetDef    GetterSetter[];
    PyTypeObject *GetType() override {return &Type;}

public:
    BlendCurvePy(BlendCurve *pcObject, PyTypeObject *T = &Type);
    static PyObject *PyMake(PyTypeObject *, PyObject *, PyObject *);
    int PyInit(PyObject* args, PyObject*k) override;


    using PointerType = BlendCurve*;

    PyObject *_repr() override;        // the representation
    std::string representation() const;

    /** @name callbacks and implementers for the python object methods */
    //@{
    /// callback for the compute() method
    static PyObject * staticCallback_compute (PyObject *self, PyObject *args);
    /// implementer for the compute() method
    PyObject*  compute(PyObject *args);
    /// callback for the setSize() method
    static PyObject * staticCallback_setSize (PyObject *self, PyObject *args);
    /// implementer for the setSize() method
    PyObject*  setSize(PyObject *args);
    //@}


    /** @name callbacks and implementers for the python object attributes */
    //@{
    //@}

    /// getter method for special attributes (e.g. dynamic ones)
    PyObject *getCustomAttributes(const char* attr) const;
    /// setter for special attributes (e.g. dynamic ones)
    /// Output: Success=1, Failure=-1, Ignore=0
    int setCustomAttributes(const char* attr, PyObject *obj);
    PyObject *_getattr(const char *attr) override;              // __getattr__ function
    int _setattr(const char *attr, PyObject *value) override;   // __setattr__ function

    /// getter for the object handled by this class
    BlendCurve *getBlendCurvePtr() const;

};

}  //namespace Surface

#endif  // SURFACE_BLENDCURVEPY_H


