# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
# source:
# - any: ['src/**/*', '!src/docs/*']


🛤️ Path:
- 'src/Mod/Path/**/*'

🏛 Arch:
- 'src/Mod/Arch/**/*'

AddonManager:
- 'src/Mod/AddonManager/**/*'

🚜 PartDesign:
- 'src/Mod/PartDesign/**/*'

':pencil2: Sketcher':
- 'src/Mod/Sketcher/**/*'

📐 Draft:
- 'src/Mod/Draft/**/*'

🧪 FEM:
- 'src/Mod/Fem/**/*'

⚙ TechDraw:
- 'src/Mod/TechDraw/**/*'

🧱 Part:  
- 'src/Mod/Part/**/*'

🥅Mesh:
- 'src/Mod/Mesh/**/*'

Spreadsheet:
- 'src/Mod/Spreadsheet/**/*'

Core:
- 'src/App/**/*'
- 'src/Base/**/*'
- 'src/Gui/**/*'