# SPDX-License-Identifier: LGPL-2.1-or-later

"""Typed public signatures for the ``FreeCADGui`` root module.

This source-adjacent stub file keeps the callable GUI module surface together
with the helper aliases, workbench support classes, and module globals those
signatures use.
"""

from __future__ import annotations

import FreeCAD as App
from collections.abc import Sequence
from enum import IntEnum
from typing import Any, ClassVar, Literal, Protocol, TypeAlias, overload

from FreeCAD import DocumentObject

_Pathish: TypeAlias = str | bytes | bytearray
_IconContent: TypeAlias = str | bytes | bytearray | memoryview
_WorkbenchMenu: TypeAlias = str | Sequence[str]
_WorkbenchCommands: TypeAlias = str | Sequence[str]

class UserInput(IntEnum):
    """Enum of keyboard, mouse, and modifier tokens used by GUI input hints."""

    ModifierShift = ...
    ModifierCtrl = ...
    ModifierAlt = ...
    ModifierMeta = ...
    KeySpace = ...
    KeyExclam = ...
    KeyQuoteDbl = ...
    KeyNumberSign = ...
    KeyDollar = ...
    KeyPercent = ...
    KeyAmpersand = ...
    KeyApostrophe = ...
    KeyParenLeft = ...
    KeyParenRight = ...
    KeyAsterisk = ...
    KeyPlus = ...
    KeyComma = ...
    KeyMinus = ...
    KeyPeriod = ...
    KeySlash = ...
    Key0 = ...
    Key1 = ...
    Key2 = ...
    Key3 = ...
    Key4 = ...
    Key5 = ...
    Key6 = ...
    Key7 = ...
    Key8 = ...
    Key9 = ...
    KeyColon = ...
    KeySemicolon = ...
    KeyLess = ...
    KeyEqual = ...
    KeyGreater = ...
    KeyQuestion = ...
    KeyAt = ...
    KeyA = ...
    KeyB = ...
    KeyC = ...
    KeyD = ...
    KeyE = ...
    KeyF = ...
    KeyG = ...
    KeyH = ...
    KeyI = ...
    KeyJ = ...
    KeyK = ...
    KeyL = ...
    KeyM = ...
    KeyN = ...
    KeyO = ...
    KeyP = ...
    KeyQ = ...
    KeyR = ...
    KeyS = ...
    KeyT = ...
    KeyU = ...
    KeyV = ...
    KeyW = ...
    KeyX = ...
    KeyY = ...
    KeyZ = ...
    KeyBracketLeft = ...
    KeyBackslash = ...
    KeyBracketRight = ...
    KeyAsciiCircum = ...
    KeyUnderscore = ...
    KeyQuoteLeft = ...
    KeyBraceLeft = ...
    KeyBar = ...
    KeyBraceRight = ...
    KeyAsciiTilde = ...
    KeyEscape = ...
    KeyTab = ...
    KeyBacktab = ...
    KeyBackspace = ...
    KeyReturn = ...
    KeyEnter = ...
    KeyInsert = ...
    KeyDelete = ...
    KeyPause = ...
    KeyPrintScr = ...
    KeySysReq = ...
    KeyClear = ...
    KeyHome = ...
    KeyEnd = ...
    KeyLeft = ...
    KeyUp = ...
    KeyRight = ...
    KeyDown = ...
    KeyPageUp = ...
    KeyPageDown = ...
    KeyShift = ...
    KeyControl = ...
    KeyMeta = ...
    KeyAlt = ...
    KeyCapsLock = ...
    KeyNumLock = ...
    KeyScrollLock = ...
    KeyF1 = ...
    KeyF2 = ...
    KeyF3 = ...
    KeyF4 = ...
    KeyF5 = ...
    KeyF6 = ...
    KeyF7 = ...
    KeyF8 = ...
    KeyF9 = ...
    KeyF10 = ...
    KeyF11 = ...
    KeyF12 = ...
    KeyF13 = ...
    KeyF14 = ...
    KeyF15 = ...
    KeyF16 = ...
    KeyF17 = ...
    KeyF18 = ...
    KeyF19 = ...
    KeyF20 = ...
    KeyF21 = ...
    KeyF22 = ...
    KeyF23 = ...
    KeyF24 = ...
    KeyF25 = ...
    KeyF26 = ...
    KeyF27 = ...
    KeyF28 = ...
    KeyF29 = ...
    KeyF30 = ...
    KeyF31 = ...
    KeyF32 = ...
    KeyF33 = ...
    KeyF34 = ...
    KeyF35 = ...
    MouseMove = ...
    MouseLeft = ...
    MouseRight = ...
    MouseMiddle = ...
    MouseScroll = ...
    MouseScrollUp = ...
    MouseScrollDown = ...

_InputSequence: TypeAlias = UserInput | tuple[UserInput, ...]

class _WorkbenchBackend(Protocol):
    """Protocol for the mutable backend object behind one GUI workbench."""

    def appendToolbar(self, name: str, cmds: Sequence[str], /) -> None:
        """Add one toolbar definition to the workbench."""
        ...

    def removeToolbar(self, name: str, /) -> None:
        """Remove one toolbar definition from the workbench."""
        ...

    def listToolbars(self) -> list[str]:
        """Return the toolbar names registered on the workbench."""
        ...

    def getToolbarItems(self) -> dict[str, list[str]]:
        """Return toolbar contents keyed by toolbar name."""
        ...

    def appendCommandbar(self, name: str, cmds: Sequence[str], /) -> None:
        """Add one command bar definition to the workbench."""
        ...

    def removeCommandbar(self, name: str, /) -> None:
        """Remove one command bar definition from the workbench."""
        ...

    def listCommandbars(self) -> list[str]:
        """Return the command bar names registered on the workbench."""
        ...

    def appendMenu(self, name: _WorkbenchMenu, cmds: _WorkbenchCommands, /) -> None:
        """Add one menu definition to the workbench."""
        ...

    def removeMenu(self, name: _WorkbenchMenu, /) -> None:
        """Remove one menu definition from the workbench."""
        ...

    def listMenus(self) -> list[str]:
        """Return the menu labels registered on the workbench."""
        ...

    def appendContextMenu(self, name: str, cmds: _WorkbenchCommands, /) -> None:
        """Add one context-menu definition to the workbench."""
        ...

    def removeContextMenu(self, name: str, /) -> None:
        """Remove one context-menu definition from the workbench."""
        ...

    def reloadActive(self) -> None:
        """Reload the active workbench presentation."""
        ...

    def name(self) -> str:
        """Return the internal backend name of the workbench."""
        ...

class Workbench:
    """Base class for Python-defined GUI workbenches."""

    MenuText: ClassVar[str]
    ToolTip: ClassVar[str]
    Icon: ClassVar[object | None]
    __Workbench__: _WorkbenchBackend

    def Initialize(self) -> None:
        """Initialize the workbench after registration."""
        ...

    def ContextMenu(self, recipient: object, /) -> None:
        """Populate the context menu for one recipient object."""
        ...

    def appendToolbar(self, name: str, cmds: Sequence[str], /) -> None:
        """Add one toolbar definition to the workbench."""
        ...

    def removeToolbar(self, name: str, /) -> None:
        """Remove one toolbar definition from the workbench."""
        ...

    def listToolbars(self) -> list[str]:
        """Return the toolbar names registered on the workbench."""
        ...

    def getToolbarItems(self) -> dict[str, list[str]]:
        """Return toolbar contents keyed by toolbar name."""
        ...

    def appendCommandbar(self, name: str, cmds: Sequence[str], /) -> None:
        """Add one command bar definition to the workbench."""
        ...

    def removeCommandbar(self, name: str, /) -> None:
        """Remove one command bar definition from the workbench."""
        ...

    def listCommandbars(self) -> list[str]:
        """Return the command bar names registered on the workbench."""
        ...

    def appendMenu(self, name: _WorkbenchMenu, cmds: _WorkbenchCommands, /) -> None:
        """Add one menu definition to the workbench."""
        ...

    def removeMenu(self, name: _WorkbenchMenu, /) -> None:
        """Remove one menu definition from the workbench."""
        ...

    def listMenus(self) -> list[str]:
        """Return the menu labels registered on the workbench."""
        ...

    def appendContextMenu(self, name: str, cmds: _WorkbenchCommands, /) -> None:
        """Add one context-menu definition to the workbench."""
        ...

    def removeContextMenu(self, name: str, /) -> None:
        """Remove one context-menu definition from the workbench."""
        ...

    def reloadActive(self) -> None:
        """Reload the active workbench presentation."""
        ...

    def name(self) -> str:
        """Return the exposed name of the workbench."""
        ...

    def GetClassName(self) -> str:
        """Return the wrapped runtime class name."""
        ...

class InputHint:
    """One user-facing message together with the input sequence that triggers it."""

    InputSequence: ClassVar[object]
    message: str
    sequences: list[_InputSequence]

    def __init__(self, message: str, *sequences: _InputSequence) -> None:
        """Create one input hint with one or more accepted input sequences."""
        ...

class _HintManager:
    """Controller for transient GUI input-hint overlays."""

    def show(self, *hints: InputHint) -> None:
        """Display one or more input hints."""
        ...

    def hide(self) -> None:
        """Hide the currently displayed input hints."""
        ...

HintManager: _HintManager
ActiveDocument: Document | None

# Scene graph and workbenches
def subgraphFromObject(obj: DocumentObject, /) -> object | None:
    """Return the Coin scene subgraph that represents one document object."""
    ...

def exportSubgraph(node: object, output: object, format: str = "VRML", /) -> None:
    """Serialize one Coin scene subgraph to an output target."""
    ...

def getSoDBVersion() -> str:
    """Return the linked Coin SoDB version string."""
    ...

def activateWorkbench(name: str, /) -> bool:
    """Activate one registered workbench by name."""
    ...

def addWorkbench(workbench: Workbench | type[Workbench], /) -> None:
    """Register one Python workbench implementation."""
    ...

def removeWorkbench(name: str, /) -> None:
    """Unregister one workbench by name."""
    ...

def getWorkbench(name: str, /) -> Workbench:
    """Return one registered workbench by name."""
    ...

def listWorkbenches() -> dict[str, Workbench]:
    """Return all registered workbenches keyed by name."""
    ...

def activeWorkbench() -> Workbench:
    """Return the currently active workbench."""
    ...

# Resources, icons, and locale
def addResourcePath(path: _Pathish, /) -> None:
    """Register an additional GUI resource search path."""
    ...

def addLanguagePath(path: _Pathish, /) -> None:
    """Register an additional translation search path."""
    ...

def addIconPath(path: _Pathish, /) -> None:
    """Register an additional icon search path."""
    ...

def addIcon(name: str, content: _IconContent, format: str = "XPM", /) -> None:
    """Register one icon payload under a symbolic name."""
    ...

def getIcon(name: str, /) -> object | None:
    """Return the cached icon object for one symbolic name."""
    ...

def isIconCached(name: str, /) -> bool:
    """Return whether one icon name is already cached."""
    ...

def updateGui() -> None:
    """Process pending GUI updates."""
    ...

def updateLocale() -> None:
    """Reload GUI translation state after locale changes."""
    ...

def getLocale() -> str:
    """Return the current GUI locale name."""
    ...

def setLocale(name: str, /) -> None:
    """Set the GUI locale name."""
    ...

def supportedLocales() -> dict[str, str]:
    """Return the locale names supported by the GUI."""
    ...

# Dialogs, preferences, and commands
def createDialog(path: str, /) -> _PyResource:
    """Load one Qt Designer UI resource and return its wrapper."""
    ...

@overload
def addPreferencePage(path: str, group: str, /) -> None:
    """Register a preference page from a `.ui` file path."""
    ...

@overload
def addPreferencePage(dialog: type[object], group: str, /) -> None:
    """Register a preference page from a Python dialog class."""
    ...

def addCommand(name: str, cmd: object, activation: str = "", /) -> None:
    """Register one GUI command object under a command name."""
    ...

def runCommand(name: str, index: int = 0, /) -> None:
    """Run one registered GUI command."""
    ...

def listCommands() -> list[str]:
    """Return the registered GUI command names."""
    ...

def isCommandActive(name: str, /) -> bool:
    """Return whether one command is active in the current GUI context."""
    ...

def SendMsgToActiveView(name: str, suppress: bool = False, /) -> None:
    """Send one named message to the active view."""
    ...

def sendMsgToFocusView(name: str, suppress: bool = False, /) -> None:
    """Send one named message to the focused view."""
    ...

def doCommand(cmd: str, /) -> None:
    """Execute one command string in the Python console context."""
    ...

def doCommandGui(cmd: str, /) -> None:
    """Execute one GUI-scoped command string."""
    ...

def doCommandEval(cmd: str, /) -> Any:
    """Evaluate one command string and return its result."""
    ...

def doCommandSkip(cmd: str, /) -> None:
    """Execute one command string without recording it in the console."""
    ...

def addModule(mod: str, /) -> None:
    """Import one module into the GUI command environment."""
    ...

def showDownloads() -> None:
    """Open the downloads or addon presentation."""
    ...

def showPreferences(grp: str = "", index: int = 0, /) -> None:
    """Open the preferences dialog to one group and page index."""
    ...

def showPreferencesByName(grp: str, pagename: str = "", /) -> None:
    """Open the preferences dialog to one group and page name."""
    ...

# Document visibility and file I/O
def hide(name: str, /) -> None:
    """Hide one named object in the active GUI document."""
    ...

def show(name: str, /) -> None:
    """Show one named object in the active GUI document."""
    ...

def hideObject(obj: DocumentObject, /) -> None:
    """Hide one document object in the GUI."""
    ...

def showObject(obj: DocumentObject, /) -> None:
    """Show one document object in the GUI."""
    ...

def open(fileName: _Pathish, /) -> None:
    """Open one document file through the GUI layer."""
    ...

def insert(fileName: _Pathish, docName: str = "", /) -> None:
    """Insert one file into an existing GUI document."""
    ...

def export(objs: Sequence[DocumentObject], fileName: _Pathish, /) -> None:
    """Export GUI document objects to one file."""
    ...

def activeDocument() -> Document | None:
    """Return the active GUI document, if any."""
    ...

def setActiveDocument(doc: str | App.Document, /) -> None:
    """Make one GUI document active."""
    ...

def editDocument() -> Document | None:
    """Return the document currently being edited in the GUI."""
    ...

def getDocument(doc: str | App.Document, /) -> Document:
    """Return one GUI document by name or application document."""
    ...

def reload(name: str, /) -> App.Document | None:
    """Reload one document by name through the GUI layer."""
    ...

def loadFile(fileName: str, module: str = "", /) -> None:
    """Load one file through the GUI import pipeline."""
    ...

# Main window and view helpers
def getMainWindow() -> _MainWindow:
    """Return the main application window wrapper."""
    ...

@overload
def activeView() -> object | None:
    """Return the current active view, creating the default 3D view when needed."""
    ...

@overload
def activeView(typeName: str, /) -> object | None:
    """Return the active view constrained to a specific FreeCAD view type name."""
    ...

def activateView(typeName: str, create: bool, /) -> None:
    """Activate one view type, optionally creating it first."""
    ...

@overload
def createViewer() -> _View3DInventor:
    """Create the default single 3D viewer."""
    ...

@overload
def createViewer(views: Literal[1], name: str = ..., /) -> _View3DInventor:
    """Create one named 3D viewer explicitly."""
    ...

@overload
def createViewer(views: int, name: str = ..., /) -> _View3DInventor | _AbstractSplitView:
    """Create a split-view layout when more than one view is requested."""
    ...

def getMarkerIndex(marker: str, size: int = 9, /) -> int:
    """Return the Coin marker index for one named marker and size."""
    ...

# Observers and edit mode
def addDocumentObserver(obj: object, /) -> None:
    """Register one GUI document observer."""
    ...

def removeDocumentObserver(obj: object, /) -> None:
    """Unregister one GUI document observer."""
    ...

def addWorkbenchManipulator(obj: object, /) -> None:
    """Register one workbench manipulator helper."""
    ...

def removeWorkbenchManipulator(obj: object, /) -> None:
    """Unregister one workbench manipulator helper."""
    ...

def listUserEditModes() -> list[str]:
    """Return the available user edit-mode names."""
    ...

def getUserEditMode() -> str:
    """Return the current user edit-mode name."""
    ...

def setUserEditMode(mode: str, /) -> bool:
    """Set the current user edit-mode by name."""
    ...

# GUI lifecycle helpers
def coinRemoveAllChildren(node: object, /) -> None:
    """Remove all Coin child nodes from one parent node."""
    ...

def suspendWaitCursor() -> None:
    """Temporarily suspend the global wait cursor."""
    ...

def resumeWaitCursor() -> None:
    """Resume the global wait cursor after suspension."""
    ...

def showMainWindow(inThread: bool = False, /) -> None:
    """Show the main application window."""
    ...

def exec_loop() -> None:
    """Enter the GUI event loop."""
    ...

def setupWithoutGUI() -> None:
    """Initialize GUI services without showing the main window."""
    ...

def embedToWindow(pointer: str, /) -> None:
    """Embed the GUI into an existing native window handle."""
    ...
