# https://packit.dev/docs/configuration/

specfile_path: package/fedora/freecad.spec

notifications:
  pull_request:
    successful_build: true

jobs:
- job: copr_build
  trigger: pull_request
  additional_repos:
    - copr://bpostle/IfcOpenShell
  targets:
  - fedora-rawhide-aarch64
  - fedora-rawhide-x86_64

# IfcOpenShell copr not built for ppc64le
#  - fedora-rawhide-ppc64le
