specfile_path: .packit_rpm/freecad.spec
files_to_sync:
    - .packit.yaml
    - src: .packit_rpm/freecad.spec
      dest: freecad.spec
actions:
  post-upstream-clone:
    - rm -rf .packit_rpm
    - git clone https://github.com/filippor/FreeCAD-fedora-packaging.git .packit_rpm
  create-archive:
    - bash -c '.packit_rpm/scripts/create-archive.sh'
downstream_package_name: freecad
upstream_tag_exclude: '.*'
notifications:
  pull_request:
    successful_build: false
additional_packages:
    - python3

jobs:
- job: copr_build
  identifier: pull_request
  trigger: pull_request
  notifications:
    pull_request:
      successful_build: false
  branch: main
  targets:
    fedora-latest-stable:
      without_opts:
      - debug_info

- job: tests
  identifier: pull_request
  trigger: pull_request
  branch: main
  targets:
    fedora-latest-stable:
      without_opts:
      - debug_info
  fmf_url: https://github.com/filippor/FreeCAD-fedora-packaging.git
  fmf_ref: main
  

- job: copr_build
  identifier: main
  trigger: commit
  branch: main
  owner: '@freecad'
  project: nightly
- job: tests
  identifier: main
  trigger: commit
  branch: main
  targets:
    fedora-latest-stable:
      without_opts:
      - debug_info
  fmf_url: https://github.com/filippor/FreeCAD-fedora-packaging.git
  fmf_ref: main
  owner: '@freecad'
  project: nightly

- job: copr_build
  identifier: release
  trigger: release
  owner: '@freecad'
  project: freecad
  targets:
    fedora-all:
      without_opts:
      - tests
