[project]
name = "FreeCAD"
version = "0.22.0"
description = "pixi instructions for FreeCAD"
authors = ["looooo <sppedflyer@gmail.com>"]
channels = ["conda-forge/label/pivy_rc", "conda-forge"]
platforms = [ "linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64" ]

[environments]
qt5 = ["qt5"]
qt6 = ["qt6"]

[dependencies]
ccache = ">=4.10.1,<5"
cmake = ">=3.28.3,<4"
coin3d = ">=4.0.2,<5"
compilers = ">=1.8.0,<2"
conda-devenv = ">=3.4.0,<4"
debugpy = ">=1.8.8,<2"
doxygen = ">=1.10.0,<2"
eigen = ">=3.4.0,<4"
fmt = ">=11.0.2,<12"
freetype = ">=2.12.1,<3"
git = ">=2.44.0,<3"
graphviz = ">=2.38.0,<13"
hdf5 = ">=1.14.3,<2"
matplotlib = ">=3.9.1,<4"
ninja = ">=1.12.1,<2"
numpy = ">=2.1.3,<3"
occt = ">=7.6.3,<8"
openssl = ">=3.4.0,<4"
pcl = ">=1.14.0,<2"
pip = ">=24.3.1,<25"
pivy = ">=0.6.9.a0,<0.7"
ply = ">=3.11,<4"
pre-commit = ">=4.0.1,<5"
pybind11 = ">=2.13.6,<3"
pyyaml = ">=6.0.2,<7"
six = ">=1.16.0,<2"
smesh = ">=9.9.0.0,<10"
swig = ">=4.2.1,<5"
xerces-c = ">=3.2.5,<4"
yaml-cpp = ">=0.8.0,<0.9"
zlib = ">=1.3.1,<2"
zstd = ">=1.5.6,<2"
scipy = ">=1.14.1,<2"

[feature.qt5.dependencies]
qt-main = "*"
pyside2 = "*"
python = "3.11"
vtk = "9.2.6"
libboost-devel = "1.82.0"
noqt6 = "*"

[feature.qt6.dependencies]
qt6-main = "*"
pyside6 = "*"
python = "3.12"
vtk = "*"
libboost-devel = "*"
noqt5 = "*"

[target.linux-64.dependencies]
kernel-headers_linux-64 = "*"
libdrm-cos6-x86_64 = "*"
libselinux-cos6-x86_64 = "*"
libsepol-cos6-x86_64 = "*"
libspnav = "*"
libx11-common-cos6-x86_64 = "*"
libx11-cos6-x86_64 = "*"
libxau-cos6-x86_64 = "*"
libxcb-cos6-x86_64 = "*"
libxdamage-cos6-x86_64 = "*"
libxext-cos6-x86_64 = "*"
libxfixes-cos6-x86_64 = "*"
libxi-cos6-x86_64 = "*"
libxi-devel-cos6-x86_64 = "*"
libxxf86vm-cos6-x86_64 = "*"
mesa-dri-drivers-cos6-x86_64 = "*"
mesa-dri1-drivers-cos6-x86_64 = "*"
mesa-libegl-cos6-x86_64 = "*"
mesa-libegl-devel-cos6-x86_64 = "*"
mesa-libgl-cos6-x86_64 = "*"
mesa-libgl-devel-cos6-x86_64 = "*"
pixman-cos6-x86_64 = "*"
sysroot_linux-64 = "*"
xorg-x11-server-common-cos6-x86_64 = "*"
xorg-x11-server-xvfb-cos6-x86_64 = "*"

[target.linux-aarch64.dependencies]
kernel-headers_linux-aarch64 = "*"
libdrm-cos7-aarch64 = "*"
libglvnd-cos7-aarch64 = "*"
libglvnd-glx-cos7-aarch64 = "*"
libselinux-cos7-aarch64 = "*"
libsepol-cos7-aarch64 = "*"
libspnav = "*"
libx11-common-cos7-aarch64 = "*"
libx11-cos7-aarch64 = "*"
libxau-cos7-aarch64 = "*"
libxcb-cos7-aarch64 = "*"
libxdamage-cos7-aarch64 = "*"
libxext-cos7-aarch64 = "*"
libxfixes-cos7-aarch64 = "*"
libxi-cos7-aarch64 = "*"
libxi-devel-cos7-aarch64 = "*"
libxxf86vm-cos7-aarch64 = "*"
mesa-dri-drivers-cos7-aarch64 = "*"
mesa-khr-devel-cos7-aarch64 = "*"
mesa-libegl-cos7-aarch64 = "*"
mesa-libegl-devel-cos7-aarch64 = "*"
mesa-libgbm-cos7-aarch64 = "*"
mesa-libgl-cos7-aarch64 = "*"
mesa-libgl-devel-cos7-aarch64 = "*"
mesa-libglapi-cos7-aarch64 = "*"
pixman-cos7-aarch64 = "*"
sysroot_linux-aarch64 = "*"
xorg-x11-server-common-cos7-aarch64 = "*"
xorg-x11-server-xvfb-cos7-aarch64 = "*"

[target.osx-64.dependencies]
[target.osx-arm64.dependencies]
[target.win-64.dependencies]

[feature.qt5.target.linux-64]
tasks = { configure = { cmd = [ "cmake", "-B", "build_qt5", "--preset", "conda-linux-debug" ], depends-on = ["initialize"]} }

[feature.qt5.target.linux-aarch64]
tasks = { configure = { cmd = [ "cmake", "-B", "build_qt5", "--preset", "conda-linux-debug" ], depends-on = ["initialize"]} }

[feature.qt5.target.osx-64]
tasks = { configure = { cmd = [ "cmake", "-B", "build_qt5", "--preset", "conda-macos-debug" ], depends-on = ["initialize"]} }

[feature.qt5.target.osx-arm64]
tasks = { configure = { cmd = [ "cmake", "-B", "build_qt5", "--preset", "conda-macos-debug" ], depends-on = ["initialize"]} }

[feature.qt5.target.win-64]
tasks = { configure = { cmd = [ "cmake", "-B", "build_qt5", "--preset", "conda-windows-debug" ], depends-on = ["initialize"]} }

[feature.qt6.target.osx-arm64.dependencies]
sed = "*"

[feature.qt6.target.osx-64.dependencies]
sed = "*"

[feature.qt6.target.linux-64.dependencies]
sed = "*"

[feature.qt6.target.linux-aarch64.dependencies]
sed = "*"

[feature.qt6.target.linux-64]
tasks = { configure = { cmd = [ "cmake", "-B", "build_qt6", "--preset", "conda-linux-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]} }

[feature.qt6.target.linux-aarch64]
tasks = { configure = { cmd = [ "cmake", "-B", "build_qt6", "--preset", "conda-linux-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on= ["initialize"]} }

[feature.qt6.target.osx-64]
tasks = { configure = { cmd = [ "cmake", "-B", "build_qt6", "--preset", "conda-macos-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]} }

[feature.qt6.target.osx-arm64]
tasks = { configure = { cmd = [ "cmake", "-B", "build_qt6", "--preset", "conda-macos-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]} }

[feature.qt6.target.win-64]
tasks = { configure = { cmd = [ "cmake", "-B", "build_qt6", "--preset", "conda-windows-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]} }

[feature.qt5.tasks]
build = { cmd = [ "cmake", "--build", "build_qt5", "-j", "2" ], depends-on = ["configure"]}
install = { cmd = [ "cmake", "--install", "build_qt5" ], depends-on = ["build"]}

[feature.qt6.tasks]
build = { cmd = [ "cmake", "--build", "build_qt6", "-j", "2" ], depends-on = ["configure"]}
install = { cmd = [ "cmake", "--install", "build_qt6" ], depends-on = ["build"]}

[tasks]
initialize = { cmd = ["git", "submodule", "update", "--init", "--recursive"]}
freecad = "FreeCAD"
