[project]
name = "FreeCAD"
version = "0.22.0"
description = "pixi instructions for FreeCAD"
authors = ["looooo <sppedflyer@gmail.com>"]
channels = ["conda-forge/label/pivy_rc", "conda-forge"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64", "win-64", "osx-64"]


[environments]
build = ["build"]

[feature.build.dependencies]
ninja = "*"
cmake = "*"
swig = "*"
python = "*"
libboost-devel = "*"
qt6-main = "*"
occt = "*"
xerces-c = "*"
zlib = "*"
vtk = "*"
eigen = "*"
pybind11 = "*"
coin3d = "*"
pyside6 = "*"
smesh = "*"
doxygen = "*"
hdf5 = "*"
freetype = "*"
pcl = "*"
six = "*"
ply = "*"
matplotlib-base = "*"
yaml-cpp = "*"
pivy = "*"
numpy = "*"
pyyaml = "*"
graphviz = "*"
clangxx = "*"
# gmsh  needs to be build for occt7.8.1

[feature.build.target.linux-64.dependencies]
sed = "*"

[feature.build.target.linux-aarch64.dependencies]
sed = "*"

[feature.build.target.osx-64.dependencies]
sed = "*"

[feature.build.target.osx-arm64.dependencies]
sed = "*"

[feature.build.target.win-64.dependencies]

[feature.build.tasks]

initialize = { cmd = ["git", "submodule", "update", "--init", "--recursive"]}

# this line is needed for shiboken to not propagate the Py_LIMITED_API definition (as freecad is not yet able to be compiled
# with Py_LIMITED_API)
patch_shiboken = "sed -i 's/Py_LIMITED_API=0x03060000;//g' $CONDA_PREFIX/lib/cmake/Shiboken6/Shiboken6Targets.cmake"
configure = { cmd = ["cmake", "-G", "Ninja", "-B", "build", "-S", ".",
                     "-D", "CMAKE_INSTALL_PREFIX:STRING=$CONDA_PREFIX",
                     "-D", "CMAKE_INSTALL_RPATH=$CONDA_PREFIX/lib",
                     "-D", "CMAKE_BUILD_TYPE:STRING=Release",
                     "-D", "QT_HOST_PATH=$CONDA_PREFIX",
                     "-D", "Boost_NO_BOOST_CMAKE:BOOL=ON",
                     "-D", "BUILD_WITH_CONDA:BOOL=ON",
                     "-D", "BUILD_FLAT_MESH:BOOL=ON",
                     "-D", "BUILD_FEM_NETGEN:BOOL=ON",
                     "-D", "FREECAD_USE_PYBIND11:BOOL=ON",
                     "-D", "FREECAD_USE_PCL:BOOL=ON",
                     "-D", "FREECAD_USE_EXTERNAL_SMESH=ON",
                     "-D", "FREECAD_USE_EXTERNAL_FMT:BOOL=OFF",
                     "-D", "DFREECAD_USE_3DCONNEXION:BOOL=OFF"
                     ], depends-on = ["initialize", "patch_shiboken"]}
build = { cmd = ["ninja", "-C", "build", "-j", "3", "install"], depends-on = ["configure"]}
build_only = { cmd = ["ninja", "-C", "build", "-j", "3", "install"]}
freecad = "FreeCAD"
