from WorkingPlane import Plane


GuiUp: int
DraftWorkingPlane: Plane
activeDraftCommand: None

# Get parameters by path
def ParamGet(path: str) -> ParameterGrp: ...


# Save parameter set to file. The default set is 'User parameter'
def saveParameter(config: str = ...) -> None: ...


# Print the version to the output
def Version() -> None: ...

def Vector(x, y, z) -> dict: ...

def Units() -> None: ...

def getResourceDir() -> str: ...
def getUserAppDataDir() -> str: ...

class ParameterGrp:
    def GetString(self, name: str, default: str = ...) -> str: ...
    def GetInt(self, name: str, default: int = ...) -> int: ...
    def GetFloat(self, name: str, default: float = ...) -> float: ...
    def GetBool(self, name: str, default: bool = ...) -> bool: ...