
	// ThumbFCStd.idl : IDL source for FCThumbs.exe
//
// This file will be processed by the MIDL tool to
// produce the type library (FCThumbs.tlb) and marshalling code.
import "oaidl.idl";
import "ocidl.idl";
  
	[
		object,
		uuid(08FB392E-6B54-4796-A960-10399D754C93),
		dual,
		helpstring("IFCStdExtractor Interface"),
		pointer_default(unique)
	]
	interface IFCStdExtractor : IDispatch
	{
	};

[
	uuid(1C52B730-EC75-423F-A300-4A42CDF1C985),
	version(1.0),
	helpstring("ThumbFCStd 1.0 Type Library")
]
library THUMBFCSTDLib 
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(287CC8A6-B380-4765-8EB1-AFC82D90DF68),
		helpstring("FCStdExtractor Class")
	]
	coclass FCStdExtractor
	{
		[default] interface IFCStdExtractor;
	};
};
