.TH FREECAD 1 "August  04, 2008" freecad "Linux User's Manual"
.SH NAME
freecad-thumbnailer \- A thumbnailer for FreeCAD project files
.SH SYNOPSIS
\fBfreecad-thumbnailer\fP [ -s \fIsize\fP ] \fIinput file\fP \fIoutput file\fP
.SH DESCRIPTION
\fBfreecad-thumbnailer\fP
is a Python script that extracts an embedded thumbnail from a FreeCAD project file.
If no thumbnail is embedded then nothing happens. According to the specification of
freedesktop.org the thumbnail image is a PNG file. The required \fBinput file\fP argument
specifies the project file where the thumbnail should be extracted from and the 
\fBoutput file\fP specifies the file where the thumbnail should be written to.
.SH OPTIONS
.TP
\fB-s \fIsize\fR
Specify the size of the image in pixel. 
.SH "SEE ALSO"
freecad(1), freecadcmd(1)
.SH AUTHOR
This manual page was written by Werner Mayer.
