name: 🐛 Report a Bug
description: File a bug report
title: "[Bug] <title>"
labels: ["🐛 bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report! Please make sure you've posted about your issue in the FreeCAD Forums before submitting here.
  - type: checkboxes
    id: existing_issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: input
    id: forum_link
    attributes:
      label: Forums discussion
      description: |
        Please start a discussion about your issue at [the FreeCAD Forum](https://forum.freecad.org) and wait for confirmation there before creating an issue.
        **Note:** Bug reports without a prior forum discussion will most likely not be accepted.
      placeholder: Paste link to forum discussion here
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of FreeCAD are you running?
      options:
        - 0.20 (Release)
        - 0.21 (Development)
    validations:
      required: true
  - type: textarea
    id: full_version
    attributes:
      label: Full version info
      description: Please use the About FreeCAD dialog to copy your full version information and paste it here.
      render: shell
    validations:
      required: true
  - type: dropdown
    id: wb
    attributes:
      label: Subproject(s) affected?
      options:
        - Addon Manager
        - Arch
        - Core
        - Draft
        - Expressions
        - FEM
        - File formats
        - GCS
        - OpenSCAD
        - Part
        - PartDesign
        - Path
        - Project Tools & Websites
        - Sketcher
        - Spreadsheet
        - Techdraw
        - Other (specify in description)
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: Please include as much detail as possible so that testers can reproduce the bug
      placeholder: Description of the problem
    validations:
      required: true
  - type: textarea
    id: anything_else
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in. To attach a FCStd file, ZIP it first (GitHub won't recognize the extension otherwise).
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/FreeCAD/FreeCAD/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
