
// This file is generated by src/Tools/generateTemplates/templateClassPyExport.py out of the XML file
// Every change you make here gets lost in the next full rebuild!
#ifndef PART_SHAPEFIX_SHAPETOLERANCEPY_H
#define PART_SHAPEFIX_SHAPETOLERANCEPY_H

#include <Base/PyObjectBase.h>
#include <ShapeFix_ShapeTolerance.hxx>
#include <string>


namespace Part
{

//===========================================================================
// ShapeFix_ShapeTolerancePy - Python wrapper
//===========================================================================

/** The python export class for ShapeFix_ShapeTolerance
 */
class PartExport ShapeFix_ShapeTolerancePy : public Base::PyObjectBase
{
protected:
    ~ShapeFix_ShapeTolerancePy() override;

public:
    static PyTypeObject   Type;
    static PyMethodDef    Methods[];
    static PyGetSetDef    GetterSetter[];
    PyTypeObject *GetType() override {return &Type;}

public:
    ShapeFix_ShapeTolerancePy(ShapeFix_ShapeTolerance *pcObject, PyTypeObject *T = &Type);
    static PyObject *PyMake(PyTypeObject *, PyObject *, PyObject *);
    int PyInit(PyObject* args, PyObject*k) override;


    using PointerType = ShapeFix_ShapeTolerance*;

    PyObject *_repr() override;        // the representation
    std::string representation() const;

    /** @name callbacks and implementers for the python object methods */
    //@{
    /// callback for the limitTolerance() method
    static PyObject * staticCallback_limitTolerance (PyObject *self, PyObject *args);
    /// implementer for the limitTolerance() method
    PyObject*  limitTolerance(PyObject *args);
    /// callback for the setTolerance() method
    static PyObject * staticCallback_setTolerance (PyObject *self, PyObject *args);
    /// implementer for the setTolerance() method
    PyObject*  setTolerance(PyObject *args);
    //@}


    /** @name callbacks and implementers for the python object attributes */
    //@{
    //@}

    /// getter method for special attributes (e.g. dynamic ones)
    PyObject *getCustomAttributes(const char* attr) const;
    /// setter for special attributes (e.g. dynamic ones)
    /// Output: Success=1, Failure=-1, Ignore=0
    int setCustomAttributes(const char* attr, PyObject *obj);
    PyObject *_getattr(const char *attr) override;              // __getattr__ function
    int _setattr(const char *attr, PyObject *value) override;   // __setattr__ function

    /// getter for the object handled by this class
    ShapeFix_ShapeTolerance *getShapeFix_ShapeTolerancePtr() const;

};

}  //namespace Part

#endif  // PART_SHAPEFIX_SHAPETOLERANCEPY_H


