# ***************************************************************************
# *   Copyright (c) 2023 0penBrain                               *
# *                                                                         *
# *   This program is free software; you can redistribute it and/or modify  *
# *   it under the terms of the GNU Lesser General Public License (LGPL)    *
# *   as published by the Free Software Foundation; either version 2 of     *
# *   the License, or (at your option) any later version.                   *
# *   for detail see the LICENCE text file.                                 *
# *                                                                         *
# *   This program is distributed in the hope that it will be useful,       *
# *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
# *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
# *   GNU Library General Public License for more details.                  *
# *                                                                         *
# *   You should have received a copy of the GNU Library General Public     *
# *   License along with this program; if not, write to the Free Software   *
# *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  *
# *   USA                                                                   *
# *                                                                         *
# ***************************************************************************

name: configure
description: "Linux: configure CMake"

inputs:
  sourcedir:
    description: "Directory where sources are stored"
    required: false
    default: ./
  builddir:
    description: "Directory where build will happen"
    required: true
  logFile:
    description: "Path for log file"
    required: true
  errorFile:
    description: "Path to error file"
    required: true
  reportFile:
    description: "Path for report file"
    required: true
  extraParameters:
    description: "Extra parameters to CMake configure"
    required: false

runs:
  using: "composite"
  steps:
    - name: Configure CMake
      id: configure
      shell: bash
      run: |
        (stdbuf -oL -eL cmake -S ${{ inputs.sourcedir }} -B ${{ inputs.builddir }} -D CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE ${{inputs.extraParameters }}) \
        2> >(tee -a ${{ inputs.errorFile }}) | tee -a ${{ inputs.logFile }}
    - name: Write report
      shell: bash
      if: always()
      run: |
        if [ ${{ steps.configure.outcome }} == 'success' ]
        then
          echo "<details><summary>:heavy_check_mark: CMake configure succeeded</summary>" >> ${{ inputs.reportFile }}
        else
          echo "<details><summary>:fire: CMake configure failed</summary>" >> ${{ inputs.reportFile }}
        fi
        echo "" >> ${{ inputs.reportFile }}
        echo "Configure Error Log (stderr output):" >> ${{ inputs.reportFile }}
        echo '```' >> ${{ inputs.reportFile }}
        cat ${{ inputs.errorFile }} >> ${{ inputs.reportFile }}
        echo '```' >> ${{ inputs.reportFile }}
        echo "Configure Log (stdout output):" >> ${{ inputs.reportFile }}
        echo '```' >> ${{ inputs.reportFile }}
        tail -n 60 ${{ inputs.logFile }} >> ${{ inputs.reportFile }}
        echo '```' >> ${{ inputs.reportFile }}
        echo "</details>">> ${{ inputs.reportFile }}
        echo "" >> ${{ inputs.reportFile }}
