# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: 2025 Dimitrios Pana <dimitriospana75@gmail.com>
# SPDX-FileNotice: Part of the FreeCAD project.

################################################################################
#                                                                              #
#   FreeCAD is free software: you can redistribute it and/or modify            #
#   it under the terms of the GNU Lesser General Public License as             #
#   published by the Free Software Foundation, either version 2.1              #
#   of the License, or (at your option) any later version.                     #
#                                                                              #
#   FreeCAD is distributed in the hope that it will be useful,                 #
#   but WITHOUT ANY WARRANTY; without even the implied warranty                #
#   of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                    #
#   See the GNU Lesser General Public License for more details.                #
#                                                                              #
#   You should have received a copy of the GNU Lesser General Public           #
#   License along with FreeCAD. If not, see https://www.gnu.org/licenses       #
#                                                                              #
################################################################################

"""
Toolpath Post-Processing and G-Code Generation for the 3D Surface Operation.

This module contains all the functions responsible for taking the raw, 3D point
data generated by the OCL drop-cutter engines and transforming it into a final,
optimized toolpath.

The pipeline is as follows:
1.  Apply Multi-pass logic to slice the toolpath into Z-layers.
2.  Filter out single-point Z-spikes caused by vertical wall artifacts.
3.  Optimize the path by removing redundant co-linear points.
4.  Generate the final G-code, including optimized, collision-safe transition moves.
"""

import math
import Path
import time

from Path.Base.Generator.surface_common import _get_ocl

__title__ = "Surface Postprocess"
__author__ = "sliptonic (Brad Collette)"
__url__ = "https://www.freecad.org"

if False:
    Path.Log.setLevel(Path.Log.Level.DEBUG, Path.Log.thisModule())
    Path.Log.trackModule(Path.Log.thisModule())
else:
    Path.Log.setLevel(Path.Log.Level.INFO, Path.Log.thisModule())


# ---------------------------------------------------------------------------
# Apply Multi-pass roughing
# ---------------------------------------------------------------------------


def apply_multipass(scan_lines, start_depth, final_depth, step_down):
    """
    Splits and clamps full-depth scan lines into multiple Z-levels for roughing.

    Args:
        scan_lines: List of scan lines, each a list of (x,y,z) tuples at full depth.
        start_depth: Top Z level to start cutting.
        final_depth: Final target Z level.
        step_down: Maximum depth per pass.

    Returns:
        A flat list of scan lines ordered by layer.
    """
    if step_down <= 0.0 or final_depth >= start_depth:
        return scan_lines

    # Generate depth levels from top to bottom
    depthparams = []
    curr_z = start_depth - step_down
    while curr_z > final_depth + 1e-5:
        depthparams.append(curr_z)
        curr_z -= step_down

    # Ensure absolute final depth is always the last pass
    if not depthparams or abs(depthparams[-1] - final_depth) > 1e-5:
        depthparams.append(final_depth)

    all_multipass_lines = []

    for i, layDep in enumerate(depthparams):
        prvDep = start_depth if i == 0 else depthparams[i - 1]

        for line in scan_lines:
            current_segment = []
            last_pt_above = None

            for pt in line:
                x, y, z_original = pt

                # A point is "above" if it was fully machined in a previous pass
                # (- 1e-4 ensures flat floors cut on the previous pass are successfully skipped here)
                is_above = z_original >= prvDep - 1e-4

                if is_above:
                    if current_segment:
                        # We were cutting, and now the tool is moving out of the cutting zone.
                        # We append the original, unclamped 3D point to the segment.
                        current_segment.append((x, y, z_original))
                        all_multipass_lines.append(current_segment)
                        current_segment = []  # Reset segment safely
                    last_pt_above = (x, y, z_original)

                else:
                    # We are IN the cutting zone (z < prvDep - 1e-4)
                    if not current_segment and last_pt_above:
                        # We just dropped into the cutting zone.
                        # Start with the last point above to ramp in seamlessly
                        current_segment.append(last_pt_above)

                    clamped_z = max(z_original, layDep)
                    current_segment.append((x, y, clamped_z))

            # End of the line - if we have an active cutting segment, save it
            if current_segment:
                all_multipass_lines.append(current_segment)

    return all_multipass_lines


# ---------------------------------------------------------------------------
# CL-point filtering via LineCLFilter
# ---------------------------------------------------------------------------


def filter_cl_points(cl_points, tolerance):
    """Use OCL LineCLFilter to remove collinear CL-points.

    Replaces the manual ``isOnLineSegment`` checks and
    ``OptimizeLinearPaths`` logic currently in SurfaceSupport.py.

    Args:
        cl_points: List of ``(x, y, z)`` tuples.
        tolerance: Collinearity tolerance (mm).

    Returns:
        Filtered list of ``(x, y, z)`` tuples.
    """
    ocl = _get_ocl()

    if len(cl_points) < 3:
        return list(cl_points)

    f = ocl.LineCLFilter()
    f.setTolerance(tolerance)

    for pt in cl_points:
        f.addCLPoint(ocl.CLPoint(pt[0], pt[1], pt[2]))

    filter_start = time.perf_counter()
    f.run()
    filter_time = time.perf_counter() - filter_start

    result = [(cl.x, cl.y, cl.z) for cl in f.getCLPoints()]

    Path.Log.debug(
        "filter_cl_points: {} -> {} points in {:.3f}s".format(
            len(cl_points), len(result), filter_time
        )
    )

    return result


# ---------------------------------------------------------------------------
# Optimize the path
# ---------------------------------------------------------------------------


def _optimize_travel(
    next_point,
    last_point,
    start_z,
    depth_offset,
    safe_z,
    clearance_z,
    optimize_ratio,
    step_down,
    horiz_feed,
    horiz_rapid,
    vert_rapid,
    safe_pdc=None,
    cutter=None,
    force_keep_down=False,
):
    """Find the shortest safe path between two scan line endpoints.

    For short transitions (≤ optimize_ratio × cutter diameter), emits a direct
    G1 feed move to the next point — the tool stays down without probing.
    Longer transitions return an empty list.

    Long-distance optimization is deferred to a future iteration.

    Args:
        next_point (tuple): (x, y, z) coordinates for the start of the next scan line.
        last_point (tuple): (x, y, z) coordinates for the end of the previous scan line.
        start_z (float): The start depth of the operation.
        depth_offset (float): Optional Z offset applied to the paths.
        safe_z (float): Safe retract height.
        clearance_z (float): Clearance height.
        optimize_ratio (float): Multiplier for the cutter diameter to determine the
            maximum allowed distance for a keep-down transition.
        step_down (float): The step-down distance per pass.
        horiz_feed (float): Horizontal cutting feed rate.
        horiz_rapid (float): Horizontal rapid feed rate.
        vert_rapid (float): Vertical rapid feed rate.
        safe_pdc (ocl.PathDropCutter, optional): Pre-built path drop cutter for
            collision detection. Reused across transitions.
        cutter (ocl.Cutter, optional): The OCL cutter object, needed to calculate
            the threshold distance (diameter × optimize_ratio).
        force_keep_down (bool): If True, forces the tool to stay down regardless
            of distance (useful for continuous patterns like ZigZag).

    Returns:
        list: A list of Path.Command objects representing the travel moves.
    """
    if safe_pdc is None or cutter is None:
        return []

    cutter_diam = cutter.getDiameter()
    dx = next_point[0] - last_point[0]
    dy = next_point[1] - last_point[1]
    xy_dist_sqrd = dx * dx + dy * dy

    if xy_dist_sqrd <= (cutter_diam * optimize_ratio) ** 2:
        transition_cmds = _dropcutter_transition(
            last_point,
            next_point,
            safe_pdc,
            start_z,
            depth_offset,
            safe_z,
            step_down,
            horiz_feed,
            force_keep_down,
        )
        if transition_cmds:
            return transition_cmds

    return []


def _dropcutter_transition(
    start,
    end,
    safe_pdc,
    start_z,
    depth_offset,
    safe_z,
    step_down,
    horiz_feed,
    force_keep_down=False,
):
    """Probes a transition path and returns surface-following G1 commands."""
    ocl = _get_ocl()
    path = ocl.Path()
    # Create a line high above the part for the drop-cutter to start from
    p1 = ocl.Point(start[0], start[1], safe_z)
    p2 = ocl.Point(end[0], end[1], safe_z)
    path.append(ocl.Line(p1, p2))

    safe_pdc.setPath(path)
    safe_pdc.run()

    cl_points = safe_pdc.getCLPoints()
    if not cl_points:
        return None

    # We only perform the aggressive climb check if we are NOT being forced to stay down.
    if not force_keep_down:
        first_transition_pt = cl_points[1]
        initial_climb = abs(first_transition_pt.z - start[2])
        step_over_transition = abs(start[2] - end[2]) < 1e-3
        above_start_z = start[2] > start_z

        # If the initial climb is more than half a step-down, it's faster to retract.
        if (
            step_down > 0 and initial_climb > (step_down / 2.0) and not step_over_transition
        ) or above_start_z:
            Path.Log.debug(
                f"Keep-down move aborted: initial climb ({initial_climb:.2f}mm) exceeds safety check."
            )
            return None  # Abort the transition

    # Use a math-based "z-floor" to prevent the tool from diving into holes or off edges
    z_floor = min(start[2], end[2])
    commands = []

    # Generate G1 moves that follow the probed surface
    for pt in cl_points[1:-1]:  # Skip first and last point to avoid duplicating moves
        z = (
            max(pt.z, z_floor) + depth_offset
        )  # Plus a small buffer to avoid touching previous on Multi-pass
        commands.append(Path.Command("G1", {"X": pt.x, "Y": pt.y, "Z": z, "F": horiz_feed}))

    # Ensure a perfect final connection to the start of the next cutting pass
    commands.append(
        Path.Command("G1", {"X": end[0], "Y": end[1], "Z": end[2] + depth_offset, "F": horiz_feed})
    )
    return commands


def _make_safe_pdc(safe_stl, cutter, final_z, sample_interval):
    """Create a reusable PathDropCutter for transition probing."""
    ocl = _get_ocl()
    safe_pdc = ocl.PathDropCutter()
    safe_pdc.setSTL(safe_stl)
    safe_pdc.setCutter(cutter)
    safe_pdc.setZ(final_z)
    safe_pdc.setSampling(sample_interval)
    return safe_pdc


# ---------------------------------------------------------------------------
# Smart Lead-in / Lead-out
# ---------------------------------------------------------------------------


def _attempt_lead_arc(line, safe_pdc, cutter, lead_feed, lift_lead_z, is_lead_in):
    """
    Attempts multiple arc lead-in or lead-out strategies in order of preference,
    returning the first successful result.
    Based on Strategy 1 and by creating a synthetic line, Strategies 2 and 3
    can produce different results.

    Strategies attempted (in order):
        1. Forward tangent arc — enters tangent to the cut direction.
           Best surface finish, most natural entry (Lead-in - Lead-out).
        2. 90 degree perpendicular arc (Lead-in only)
           This strategy attempts to enter from the side
        3. Reverse tangent arc — enters from the opposite direction (Lead-in only).
           Catches entries where the forward side is blocked but the
           back is open (common on lines starting at a far boundary).
        4. Retreat to previous point (Lead-out only).

    All strategies reuse _get_material_side_vector and _generate_lead_arc
    with parameter variations — no additional probing infrastructure needed.

    Args:
        line (list): Scan line as a list of (x, y, z) tuples. Must have >= 2 points.
        safe_pdc (ocl.PathDropCutter): Pre-configured, reusable drop-cutter.
        cutter (ocl.Cutter): Active cutter.
        lead_feed (float): Feed rate for the arc move (mm/min).

    Returns:
        tuple: (list_of_Path.Commands, entry_point) on success,
               or ([], None) if all strategies fail.
    """
    if not line or len(line) < 2:
        return [], None

    radius = cutter.getDiameter() / 2.0

    # Strategy 1: Forward tangent arc (Lead-in and Lead-out)
    # Standard entry/exit — tangent to the cut direction at full radius.
    cmds, lead = _generate_lead_arc(line, safe_pdc, cutter, lead_feed, lift_lead_z, is_lead_in)
    if lead:
        Path.Log.debug("LeadIn/LeadOut: forward tangent arc")
        return cmds, lead

    if is_lead_in:
        # Strategy 2: (Lead-in only)
        # Construct a synthetic line that is rotated 90 degrees to the original cut direction.
        p_attach = line[0]
        p_next = line[1]
        # Calculate the direction vector perpendicular to the cut.
        dx = p_next[0] - p_attach[0]
        dy = p_next[1] - p_attach[1]
        mag = math.hypot(dx, dy)
        if mag > 1e-6:
            perp_dir_x, perp_dir_y = -dy / mag, dx / mag
            p_perpendicular = (p_attach[0] + perp_dir_x, p_attach[1] + perp_dir_y, p_attach[2])
            line_90_deg = [p_attach, p_perpendicular] + line[1:]

            cmds, lead = _generate_lead_arc(
                line_90_deg, safe_pdc, cutter, lead_feed, lift_lead_z, is_lead_in=True
            )
            if lead:
                Path.Log.debug("LeadIn: Succeeded with 90-degree perpendicular arc.")
                return cmds, lead

        # Strategy 3
        # Reverse tangent arc (Lead-in only)
        # Construct a synthetic reversed line: same points, direction inverted.
        reversed_line = [
            p_attach,
            (
                p_attach[0] - (p_next[0] - p_attach[0]),
                p_attach[1] - (p_next[1] - p_attach[1]),
                p_attach[2],
            ),
        ] + line[1:]

        cmds, lead = _generate_lead_arc(
            reversed_line, safe_pdc, cutter, lead_feed, lift_lead_z, is_lead_in
        )
        if lead:
            Path.Log.debug("LeadIn: reverse tangent arc")
            return cmds, lead

    # Strategy 4: (Lead-out only)
    # Retreat to previous point and up
    else:
        p_attach = line[-1]
        p_prev = line[-2]
        lead = (p_prev[0], p_prev[1], p_attach[2] + radius)
        Path.Log.debug("LeadOut: retreat to previous point")
        return [
            Path.Command("G1", {"X": lead[0], "Y": lead[1], "Z": lead[2], "F": lead_feed})
        ], lead

    # Note: Other strategies can be added here.

    # All strategies failed
    Path.Log.debug("LeadIn/LeadOut: all arc strategies failed — falling back to helix or plunge")
    return [], None


def _generate_lead_arc(line, safe_pdc, cutter, lead_feed, lift_lead_z, is_lead_in):
    """
    Generates a 90-degree tangent lead-in or lead-out arc at constant Z.

    The arc entry/exit point comes directly from _get_material_side_vector,
    which already positions it one radius ahead/behind and one radius
    perpendicular — no duplicate geometry calculations needed here.

    The arc is purely horizontal (constant Z = p_attach[2]) so it is safe
    on all controllers with no helical interpolation required.

    Args:
        line (list): Scan line as a list of (x, y, z) tuples. Must have >= 2 points.
        safe_pdc (ocl.PathDropCutter): Pre-configured drop-cutter for probing.
        cutter (ocl.Cutter): Active cutter — diameter used for arc radius.
        lead_feed (float): Feed rate for the arc move (mm/min).
        is_lead_in (bool): True = lead-in arc; False = lead-out arc.

    Returns:
        tuple: (list_of_Path.Commands, entry_exit_point_or_None)
            Lead-in:  commands move FROM entry_point TO p_attach; returns entry_point.
            Lead-out: commands move FROM p_attach TO exit_point; returns exit_point.
            On failure: returns ([], None).
    """
    if not line or len(line) < 2:
        return [], None

    radius = cutter.getDiameter() / 2.0

    # 1. Identify the attachment point and reference segment
    if is_lead_in:
        p_attach = line[0]
        seg_start, seg_end = line[0], line[1]
    else:
        p_attach = line[-1]
        seg_start, seg_end = line[-2], line[-1]

    # 2. Probe for a clear side — get away_vec, arc direction, and entry/exit point
    away_vec, arc_direction_is_cw, entry_exit_2d = _get_material_side_vector(
        seg_start, seg_end, cutter, safe_pdc, lift_lead_z, is_lead_in=is_lead_in
    )
    if away_vec is None:
        return [], None  # No clear side — caller falls back to straight plunge

    # 3. Arc entry/exit point at constant Z (no surface projection needed)
    cut_z = p_attach[2]
    entry_exit_point = (
        entry_exit_2d[0],
        entry_exit_2d[1],
        cut_z + lift_lead_z,
    )  # lift_lead also in commands for Lead-out below

    # 4. Arc center — one radius away from p_attach in the away_vec direction
    center_x = p_attach[0] + away_vec[0] * radius
    center_y = p_attach[1] + away_vec[1] * radius

    # 5. G2 = CW, G3 = CCW — standard G-code convention
    arc_cmd_str = "G2" if arc_direction_is_cw else "G3"

    commands = []

    if is_lead_in:
        # Move FROM entry_exit_point TO p_attach.
        # I, J = offsets from arc start (entry_exit_point) to center.
        i_offset = center_x - entry_exit_point[0]
        j_offset = center_y - entry_exit_point[1]
        commands.append(
            Path.Command(
                arc_cmd_str,
                {
                    "X": p_attach[0],
                    "Y": p_attach[1],
                    "Z": cut_z,
                    "I": i_offset,
                    "J": j_offset,
                    "F": lead_feed,
                },
            )
        )
        return commands, entry_exit_point

    else:  # Lead-out
        # Move FROM p_attach TO entry_exit_point.
        # I, J = offsets from arc start (p_attach) to center.
        i_offset = center_x - p_attach[0]
        j_offset = center_y - p_attach[1]
        commands.append(
            Path.Command(
                arc_cmd_str,
                {
                    "X": entry_exit_point[0],
                    "Y": entry_exit_point[1],
                    "Z": cut_z + lift_lead_z,
                    "I": i_offset,
                    "J": j_offset,
                    "F": lead_feed,
                },
            )
        )
        return commands, entry_exit_point


def _get_material_side_vector(
    p_segment_start, p_segment_end, cutter, safe_pdc, lift_lead_z, is_lead_in
):
    """
    Probes left and right of a path segment to find a clear "air" side for
    a lead-in or lead-out arc, and returns the chosen probe point as the
    arc entry/exit point — avoiding any duplicate geometry calculations in
    _generate_lead_arc.

    Uses a short-circuit probing strategy to minimize OCL calls:
      1. Probe left endpoint — fail → skip to right side
      2. Probe left midpoint — fail → try right side
      3. If both left checks pass → commit to left (best case: 2 probes total)
      4. Right side follows the same two-step pattern
      5. If all checks fail → return (None, None, None), caller falls back
         to a straight plunge

    For each side, the two probe points are:
      - Arc endpoint: one radius ahead/behind and one radius perpendicular
        from the attachment point — the exact arc entry/exit coordinate.
      - Arc midpoint: the geometrically furthest point of the 90° arc sweep,
        at 45° between the endpoint and the attachment point on the circle.
        This is the most exposed point during the arc move.

    Args:
        p_segment_start (tuple): (x, y, z) start of the reference segment.
        p_segment_end (tuple): (x, y, z) end of the reference segment.
        cutter (ocl.Cutter): Active cutter — diameter used to scale offsets.
        safe_pdc (ocl.PathDropCutter): Pre-configured, reusable drop-cutter.
        is_lead_in (bool): True = probe before segment start; False = probe after end.

    Returns:
        tuple: (away_vec, arc_direction_is_cw, entry_exit_2d)
            away_vec (tuple): Normalized 2D vector pointing toward "air".
            arc_direction_is_cw (bool): True = G2, False = G3.
            entry_exit_2d (tuple): (x, y) of the arc entry or exit point.
        Or (None, None, None) if no clear side is found.
    """
    # 1. Compute the 2D direction vector of the segment
    dx = p_segment_end[0] - p_segment_start[0]
    dy = p_segment_end[1] - p_segment_start[1]
    mag = math.hypot(dx, dy)
    if mag < 1e-6:
        return None, None, None  # Segment too short — no meaningful direction

    dir_x, dir_y = dx / mag, dy / mag

    radius = cutter.getDiameter() / 2.0
    cut_z = p_segment_start[2] if is_lead_in else p_segment_end[2]
    reference_z = cut_z + lift_lead_z + 1.0
    clearance_threshold = cut_z + 0.001

    # 2. Shift the probe base one full radius along the cut direction so the
    # sample points sit inside the actual arc footprint, not on the edge.
    if is_lead_in:
        p_attach = p_segment_start
        probe_base_x = p_segment_start[0] - dir_x * radius
        probe_base_y = p_segment_start[1] - dir_y * radius
    else:
        p_attach = p_segment_end
        probe_base_x = p_segment_end[0] + dir_x * radius
        probe_base_y = p_segment_end[1] + dir_y * radius

    # 3. Perpendicular unit vectors (left and right of travel direction)
    perp_l_x, perp_l_y = -dir_y, dir_x  # 90° CCW
    perp_r_x, perp_r_y = dir_y, -dir_x  # 90° CW

    # 4. Arc endpoints — one radius perpendicular from the probe base.
    # These are the exact arc entry/exit coordinates reused in _generate_lead_arc.
    p_left_2d = (probe_base_x + perp_l_x * radius, probe_base_y + perp_l_y * radius)
    p_right_2d = (probe_base_x + perp_r_x * radius, probe_base_y + perp_r_y * radius)

    # 5. Helper: true geometric midpoint of the 90° arc between p_arc_end
    # and p_attach, at 45° around the circle from each endpoint.
    def _arc_midpoint(p_arc_end, perp_x, perp_y):
        center_x = p_attach[0] + perp_x * radius
        center_y = p_attach[1] + perp_y * radius
        to_mid_x = ((p_arc_end[0] + p_attach[0]) / 2.0) - center_x
        to_mid_y = ((p_arc_end[1] + p_attach[1]) / 2.0) - center_y
        to_mid_mag = math.hypot(to_mid_x, to_mid_y)
        if to_mid_mag < 1e-9:
            return p_arc_end  # Degenerate — fall back to endpoint
        return (
            center_x + (to_mid_x / to_mid_mag) * radius,
            center_y + (to_mid_y / to_mid_mag) * radius,
        )

    # 6. Short-circuit probing — commit to a side as soon as both probe points its
    # checks pass, skipping the opposite side entirely.
    def _side_clear(p_end_2d, perp_x, perp_y):
        # Probe endpoint then midpoint. Returns True only if both are clear.
        z_end = _probe_surface_z(p_end_2d, reference_z, safe_pdc)
        z_end = z_end if z_end is not None else -1e9
        if z_end >= clearance_threshold + lift_lead_z:
            return False  # Endpoint obstructed — skip midpoint probe
        z_mid = _probe_surface_z(_arc_midpoint(p_end_2d, perp_x, perp_y), reference_z, safe_pdc)
        z_mid = z_mid if z_mid is not None else -1e9
        return z_mid < clearance_threshold + (lift_lead_z / 2)

    # Try left first, then right — commit on first fully clear side
    if _side_clear(p_left_2d, perp_l_x, perp_l_y):
        away_vec, entry_exit_2d = (perp_l_x, perp_l_y), p_left_2d
    elif _side_clear(p_right_2d, perp_r_x, perp_r_y):
        away_vec, entry_exit_2d = (perp_r_x, perp_r_y), p_right_2d
    else:
        return None, None, None  # Both sides obstructed — fall back to straight plunge

    # 7. Derive arc direction via 2D cross product of (cut_dir × away_vec).
    cross = dir_x * away_vec[1] - dir_y * away_vec[0]
    arc_direction_is_cw = cross < 0

    return away_vec, arc_direction_is_cw, entry_exit_2d


def _probe_surface_z(point_2d, reference_z, safe_pdc):
    """
    Returns the OCL drop-cutter Z height at a given 2D XY position.

    Uses a tiny non-degenerate line segment (1e-4 mm XY offset) so that
    PathDropCutter always has a valid segment to sample from. A zero-length
    line (p == p) causes OCL to return no points or behave unpredictably.

    Args:
        point_2d (tuple): The (x, y) coordinate to probe.
        reference_z (float): Drop-start height; should be safely above the surface.
        safe_pdc (ocl.PathDropCutter): Pre-configured, reusable drop-cutter instance.

    Returns:
        float: The probed Z height, or None if OCL returns no points.
    """
    ocl = _get_ocl()
    path = ocl.Path()
    p_start = ocl.Point(point_2d[0], point_2d[1], reference_z)
    p_end = ocl.Point(point_2d[0] + 1e-4, point_2d[1], reference_z)
    path.append(ocl.Line(p_start, p_end))
    safe_pdc.setPath(path)
    safe_pdc.run()
    cl_points = safe_pdc.getCLPoints()
    return cl_points[0].z if cl_points else None


# ---------------------------------------------------------------------------
# Volumetric Feed Rates
# ---------------------------------------------------------------------------


def _generate_volumetric_cut_commands(
    line, depth_offset, horiz_feed, vert_feed, layer_start_z, layer_target_z, volumetric_percent
):
    """
    Generate G-code commands for a single scan line using a Volumetric feed rate.

    This function converts 3D toolpath coordinates into Path.Command objects while
    dynamically adjusting the feed rate based on the slope and depth of the cut.
    It utilizes a 1-point lookahead kinematic preview to progressively blend feed
    rates, allowing the machine to brake early before steep plunges.

    A threshold filter is applied to prevent micro-adjustments from bloating the
    final G-code file.

    Args:
        line (list): Scan line as a list of (x, y, z) tuples.
        depth_offset (float): Global Z-offset to apply to the toolpath.
        horiz_feed (float): Base horizontal cutting feed rate (mm/s).
        vert_feed (float): Vertical plunge feed rate (mm/s).
        layer_start_z (float): The top Z-boundary of the current roughing pass.
        layer_target_z (float): The bottom Z-boundary of the current roughing pass.
        volumetric_percent (float): The percentage value defining the maximum speed boost
                                 at the top of a shallow cut (e.g., 50 provides a 50%
                                 speed increase; 0 disables the boost).

    Returns:
        list: A list of FreeCAD Path.Command objects representing the cutting move.
    """
    commands = []

    if not line:
        return commands

    # Volumetric boost factor
    boost_factor = 1.0 + (volumetric_percent / 100.0)
    threshold = 0.5  # Ignore feed changes smaller than 0.5 mm/s (30 mm/min)

    # Setup the very first point
    first_pt = line[0]
    z = first_pt[2] + depth_offset

    # Find the starting feed rate using the helper
    # We fake a prev_pt that is flat to avoid triggering a plunge penalty on the first move
    fake_prev = (first_pt[0] - 0.01, first_pt[1], first_pt[2])
    initial_feed = _get_segment_target_feed(
        fake_prev, first_pt, horiz_feed, vert_feed, layer_start_z, layer_target_z, boost_factor
    )

    current_feed = round(initial_feed, 2)
    commands.append(
        Path.Command("G1", {"X": first_pt[0], "Y": first_pt[1], "Z": z, "F": current_feed})
    )

    # Loop through the rest of the segments
    for i in range(1, len(line)):
        pt = line[i]
        prev_pt = line[i - 1]
        z = pt[2] + depth_offset

        # Calculate feed for This segment based on height and plunge angle
        curr_target = _get_segment_target_feed(
            prev_pt, pt, horiz_feed, vert_feed, layer_start_z, layer_target_z, boost_factor
        )

        # Lookahead: Only look ahead to pre-brake for steep upcoming downhill drops
        if i + 1 < len(line):
            next_pt = line[i + 1]
            next_target = _get_segment_target_feed(
                pt, next_pt, horiz_feed, vert_feed, layer_start_z, layer_target_z, boost_factor
            )
            # Pre-brake if the next move is significantly slower
            if (curr_target - next_target) > threshold * 2:
                curr_target = (curr_target + next_target) / 2.0

        # Threshold Cache: Only update if the change is significant enough
        if abs(curr_target - current_feed) >= threshold:
            calculated_feed = round(curr_target, 2)
            commands.append(
                Path.Command("G1", {"X": pt[0], "Y": pt[1], "Z": z, "F": calculated_feed})
            )
            current_feed = calculated_feed  # Update the cache
        else:
            # Same speed, just output the coordinates
            commands.append(Path.Command("G1", {"X": pt[0], "Y": pt[1], "Z": z}))

    return commands


def _get_segment_target_feed(
    prev_pt, pt, horiz_feed, vert_feed, layer_start_z, layer_target_z, boost_factor
):
    """
    Calculate the ideal feed rate for a single linear segment based on depth and slope.

    This acts as a volumetric chip-load optimizer. It applies a speed boost when the
    tool is near the top of the pass layer (less material engagement), and scales
    down to the baseline horizontal feed at the target depth. It also applies a
    kinematic penalty based on the 3D angle of the segment (slowing down for plunges
    and stripping boosts for steep climbs).

    Note: This is a pure math function. It does not apply rounding or thresholding.

    Args:
        prev_pt (tuple): The starting (x, y, z) coordinate of the segment.
        pt (tuple): The ending (x, y, z) coordinate of the segment.
        horiz_feed (float): Base horizontal cutting feed rate (mm/s).
        vert_feed (float): Vertical plunge feed rate (mm/s).
        layer_start_z (float): The top Z-boundary of the current roughing pass.
        layer_target_z (float): The bottom Z-boundary of the current roughing pass.
        boost_factor (float): The calculated decimal multiplier applied to the horizontal
                              feed rate at the top of the layer (e.g., 1.5 for a 50% increase).
                              A value of 1.0 completely disables volumetric scaling.

    Returns:
        float: The raw, calculated target feed rate for this specific movement.
    """
    # 1. Base feed determined strictly by absolute Z-height
    total_depth = layer_start_z - layer_target_z
    if total_depth > 1e-5:
        clamped_z = max(layer_target_z, min(layer_start_z, pt[2]))
        z_ratio = (clamped_z - layer_target_z) / total_depth
    else:
        z_ratio = 0.0

    # Boost the horizontal feed based on how high up we are
    base_target = horiz_feed + (horiz_feed * (boost_factor - 1.0) * z_ratio)

    # 2. Plunge Penalty (Only evaluate if we are going downhill)
    dx = pt[0] - prev_pt[0]
    dy = pt[1] - prev_pt[1]
    dz = pt[2] - prev_pt[2]
    dist_3d = math.hypot(dx, dy, dz)

    if dist_3d > 1e-6 and dz < -1e-5:
        # Plunging downwards: blend between the base_target and vert_feed
        z_angle_ratio = abs(dz) / dist_3d
        return base_target - ((base_target - vert_feed) * z_angle_ratio)

    # If flat or climbing, just return the height-based feed!
    return base_target


# ---------------------------------------------------------------------------
# G-code generation from drop-cutter data
# ---------------------------------------------------------------------------


def scan_lines_to_gcode(
    scan_lines,
    sample_interval,
    horiz_feed,
    vert_feed,
    vert_rapid,
    horiz_rapid,
    safe_z,
    clearance_z,
    start_z,
    final_z,
    step_down,
    options,
):
    """
    Convert multiple scan lines of CL-points to G-code with transitions,
    optional smart lead-in/out, and optional keep-down optimization.

    Each scan line is a list of ``(x, y, z)`` tuples.  Travel moves are
    inserted between scan lines.

    Args:
        scan_lines (list): List of scan lines, each a list of ``(x, y, z)`` tuples.
        sample_interval (float): The sampling distance between points on the scan line.
        horiz_feed (float): Horizontal feed rate.
        vert_feed (float): Vertical plunge feed rate.
        vert_rapid (float): Vertical rapid feed rate.
        horiz_rapid (float): Horizontal rapid feed rate.
        safe_z (float): Safe height for short transitions.
        clearance_z (float): Clearance height for long transitions.
        start_z (float): Start Depth.
        final_z (float): Final depth.
        step_down (float): Step Down height.
        options (dict): Dictionary of optional features containing:
            - depth_offset (float): Optional Z offset.
            - optimize_transitions (bool): If True, short transitions (≤ optimize_ratio × cutter
              diameter) use a direct G1 feed move instead of retracting. Longer transitions
              fall back to a full safe_z retract.
            - optimize_ratio (float): Multiplier for the cutter diameter to set the maximum
              keep-down distance.
            - safe_stl (ocl.STLSurf): Optional STL surface for transition optimization collisions.
            - cutter (ocl.Cutter): Optional OCL cutter for transition optimization.
            - force_keep_down (bool): If True, forces the tool to stay down during transitions
              (useful for specific path patterns like ZigZag).
            - use_smart_leads (bool): If True and not optimize_transitions, uses the smart
              Lead-in/out algorithm.
            - lead_feed_percent (float): Feed rate for lead-in/out arcs, expressed as a
              percentage of the horiz_feed.
            - lift_lead_z (float): Optional vertical lift applied during the lead moves.
            - volumetric_percent (float): Scales the horizontal feed rate at the top of the cut
              as a percentage (0 disables the depth boost).
            - is_multipass (bool): True if the job requires multiple step-down passes.

    Returns:
        List of ``Path.Command``.
    """
    if not scan_lines:
        return []

    safe_pdc = last_point = None

    depth_offset = options["depth_offset"]
    optimize_transitions = options["optimize_transitions"]
    optimize_ratio = options["optimize_ratio"]
    safe_stl = options["safe_stl"]
    cutter = options["cutter"]
    force_keep_down = options["force_keep_down"]
    use_smart_leads = options["use_smart_leads"]
    lead_feed_percent = options["lead_feed_percent"]
    lift_lead_z = options["lift_lead_z"]
    volumetric_percent = options.get("volumetric_percent", 25)
    is_multipass = options["is_multipass"]

    if use_smart_leads:
        lead_feed = horiz_feed * (lead_feed_percent / 100)

        msg = "Smart Lead-In/Out enabled. Please verify the path visually for collision safety."

        if optimize_transitions:
            msg += " 'Keep Tool Down' has been disabled to allow leads."
            optimize_transitions = False
        Path.Log.warning(msg)

    if (optimize_transitions or use_smart_leads) and safe_stl is not None and cutter is not None:
        safe_pdc = _make_safe_pdc(safe_stl, cutter, final_z, sample_interval)

    if volumetric_percent > 0:
        vol_msg = (
            f"Volumetric Feed enabled ({volumetric_percent}% boost). "
            "Ensure 'Start Depth', 'Final Depth', and 'Step Down' tightly bound "
            "your actual stock material for accurate depth-based acceleration."
        )
        Path.Log.info(vol_msg)

    commands = []
    commands.append(Path.Command("G0", {"Z": clearance_z, "F": vert_rapid}))

    # Setup initial multi-pass layer boundaries
    current_layer_start = start_z
    current_layer_target = start_z - step_down if is_multipass else final_z

    for line in scan_lines:
        if not line:
            continue

        # Volumetric feed Layer Bounds
        if is_multipass:
            min_range = min(50, len(line))

            for i in range(min_range):
                pt = line[i]
                if pt[2] < current_layer_target - 1e-2:
                    # If the tool drops into the next level, step the tracking bounds down
                    current_layer_start = current_layer_target
                    current_layer_target -= step_down
                    continue

        lead_in_cmds = []
        first_point = line[0]  # First Point

        # A. Generate Lead-in
        if use_smart_leads and safe_pdc:
            lead_in_cmds, lead_start = _attempt_lead_arc(
                line, safe_pdc, cutter, lead_feed, lift_lead_z, is_lead_in=True
            )
            if lead_start:
                first_point = lead_start

        # B. Handle Transition
        if last_point is not None:
            travel_cmds = None
            if optimize_transitions:
                travel_cmds = _optimize_travel(
                    first_point,
                    last_point,
                    start_z,
                    depth_offset,
                    safe_z,
                    clearance_z,
                    optimize_ratio,
                    step_down,
                    horiz_feed,
                    horiz_rapid,
                    vert_rapid,
                    safe_pdc,
                    cutter,
                    force_keep_down,
                )

            # Fallback Logic
            if not travel_cmds:
                travel_cmds = [
                    Path.Command("G0", {"Z": safe_z, "F": vert_rapid}),
                    Path.Command(
                        "G0", {"X": first_point[0], "Y": first_point[1], "F": horiz_rapid}
                    ),
                ]
            commands.extend(travel_cmds)
        else:  # First move of operation
            commands.append(
                Path.Command("G0", {"X": first_point[0], "Y": first_point[1], "F": horiz_rapid})
            )

        # C. Plunge to start of lead/cut
        commands.append(Path.Command("G1", {"Z": first_point[2] + depth_offset, "F": vert_feed}))

        # D. Add Lead-in G-code
        commands.extend(lead_in_cmds)

        # E. Cut along the scan line - Apply Volumetric Feed
        cut_cmds = _generate_volumetric_cut_commands(
            line,
            depth_offset,
            horiz_feed,
            vert_feed,
            current_layer_start,
            current_layer_target,
            volumetric_percent,
        )
        commands.extend(cut_cmds)

        # F. Generate Lead-out
        if use_smart_leads and safe_pdc:
            lead_out_cmds, lead_end = _attempt_lead_arc(
                line, safe_pdc, cutter, lead_feed, lift_lead_z, is_lead_in=False
            )
            commands.extend(lead_out_cmds)
            last_point = lead_end if lead_end else line[-1]
        else:
            last_point = line[-1]

    return commands
