project-includes = [
    "smoke.py",
    "draft_protocols.py",
    "../../../Mod/Draft/draftmake/make_arc_3points.py",
    "../../../Mod/Draft/draftmake/make_bezcurve.py",
    "../../../Mod/Draft/draftmake/make_bspline.py",
    "../../../Mod/Draft/draftmake/make_circle.py",
    "../../../Mod/Draft/draftmake/make_clone.py",
    "../../../Mod/Draft/draftmake/make_ellipse.py",
    "../../../Mod/Draft/draftmake/make_fillet.py",
    "../../../Mod/Draft/draftmake/make_line.py",
    "../../../Mod/Draft/draftmake/make_point.py",
    "../../../Mod/Draft/draftmake/make_polygon.py",
    "../../../Mod/Draft/draftmake/make_rectangle.py",
    "../../../Mod/Draft/draftmake/make_shape2dview.py",
    "../../../Mod/Draft/draftmake/make_shapestring.py",
    "../../../Mod/Draft/draftmake/make_text.py",
    "../../../Mod/Draft/draftmake/make_wire.py",
    "../../../Mod/Draft/draftobjects/bezcurve.py",
    "../../../Mod/Draft/draftobjects/bspline.py",
    "../../../Mod/Draft/draftobjects/circle.py",
    "../../../Mod/Draft/draftobjects/clone.py",
    "../../../Mod/Draft/draftobjects/ellipse.py",
    "../../../Mod/Draft/draftobjects/fillet.py",
    "../../../Mod/Draft/draftobjects/point.py",
    "../../../Mod/Draft/draftobjects/polygon.py",
    "../../../Mod/Draft/draftobjects/rectangle.py",
    "../../../Mod/Draft/draftobjects/shape2dview.py",
    "../../../Mod/Draft/draftobjects/shapestring.py",
    "../../../Mod/Draft/draftobjects/text.py",
    "../../../Mod/Draft/draftobjects/type_hints.py",
    "../../../Mod/Draft/draftobjects/wire.py",
    "../../../Mod/Draft/draftutils/groups.py",
    "../../../Mod/Draft/draftutils/type_hints.py",
]
search-path = ["../generated/stubs", "../../../Mod/Draft", "../../../Mod/BIM", "../../../3rdParty"]
ignore-missing-imports = ["pivy", "Draft_rc"]
