# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plate_parameters.ui'
#
# Created: Tue Aug 21 17:01:39 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DialogPlateDimensions(object):
    def setupUi(self, DialogPlateDimensions):
        DialogPlateDimensions.setObjectName(_fromUtf8("DialogPlateDimensions"))
        DialogPlateDimensions.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogPlateDimensions.resize(591, 172)
        self.widget = QtGui.QWidget(DialogPlateDimensions)
        self.widget.setGeometry(QtCore.QRect(10, 10, 572, 151))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.thickness = QtGui.QDoubleSpinBox(self.widget)
        self.thickness.setMinimumSize(QtCore.QSize(130, 0))
        self.thickness.setMaximumSize(QtCore.QSize(16777210, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.thickness.setFont(font)
        self.thickness.setMinimum(-100000.0)
        self.thickness.setMaximum(100000.0)
        self.thickness.setProperty(_fromUtf8("value"), 0.0)
        self.thickness.setObjectName(_fromUtf8("thickness"))
        self.horizontalLayout.addWidget(self.thickness)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.width = QtGui.QDoubleSpinBox(self.widget)
        self.width.setMinimumSize(QtCore.QSize(130, 0))
        self.width.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.width.setFont(font)
        self.width.setMinimum(-100000.0)
        self.width.setMaximum(100000.0)
        self.width.setProperty(_fromUtf8("value"), 0.0)
        self.width.setObjectName(_fromUtf8("width"))
        self.horizontalLayout_2.addWidget(self.width)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.length = QtGui.QDoubleSpinBox(self.widget)
        self.length.setMinimumSize(QtCore.QSize(130, 0))
        self.length.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.length.setFont(font)
        self.length.setMinimum(-100000.0)
        self.length.setMaximum(100000.0)
        self.length.setProperty(_fromUtf8("value"), 0.0)
        self.length.setObjectName(_fromUtf8("length"))
        self.horizontalLayout_3.addWidget(self.length)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.flytobuyratio = QtGui.QLCDNumber(self.widget)
        self.flytobuyratio.setSmallDecimalPoint(False)
        self.flytobuyratio.setNumDigits(3)
        self.flytobuyratio.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.flytobuyratio.setProperty(_fromUtf8("value"), 10.0)
        self.flytobuyratio.setProperty(_fromUtf8("intValue"), 10)
        self.flytobuyratio.setObjectName(_fromUtf8("flytobuyratio"))
        self.verticalLayout_2.addWidget(self.flytobuyratio)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)

        self.retranslateUi(DialogPlateDimensions)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogPlateDimensions.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogPlateDimensions.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogPlateDimensions)
        DialogPlateDimensions.setTabOrder(self.thickness, self.width)
        DialogPlateDimensions.setTabOrder(self.width, self.length)
        DialogPlateDimensions.setTabOrder(self.length, self.buttonBox)

    def retranslateUi(self, DialogPlateDimensions):
        DialogPlateDimensions.setWindowTitle(QtGui.QApplication.translate("DialogPlateDimensions", "Adjust Plate dimensions", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogPlateDimensions", "Plate thickness [mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogPlateDimensions", "Plate width [mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogPlateDimensions", "Plate length [mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DialogPlateDimensions", "Fly to Buy Ratio based on current geometry and selected plate dimensions", None, QtGui.QApplication.UnicodeUTF8))

