# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User_Interface_Mach_Dist.ui'
#
# Created: Fri Apr 15 11:22:01 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName(_fromUtf8("dialog"))
        dialog.resize(658, 430)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog.sizePolicy().hasHeightForWidth())
        dialog.setSizePolicy(sizePolicy)
        dialog.setMinimumSize(QtCore.QSize(658, 430))
        dialog.setMaximumSize(QtCore.QSize(658, 430))
        self.gridLayout_8 = QtGui.QGridLayout(dialog)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.groupBox_3 = QtGui.QGroupBox(dialog)
        self.groupBox_3.setMinimumSize(QtCore.QSize(282, 161))
        self.groupBox_3.setMaximumSize(QtCore.QSize(282, 161))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_24 = QtGui.QLabel(self.groupBox_3)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 0, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_3)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 0, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_3)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.spinBox_misalignment_x_from = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_misalignment_x_from.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_misalignment_x_from.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_misalignment_x_from.setMinimum(-99)
        self.spinBox_misalignment_x_from.setObjectName(_fromUtf8("spinBox_misalignment_x_from"))
        self.gridLayout.addWidget(self.spinBox_misalignment_x_from, 1, 0, 1, 1)
        self.spinBox_misalignment_x_to = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_misalignment_x_to.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_misalignment_x_to.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_misalignment_x_to.setMinimum(-99)
        self.spinBox_misalignment_x_to.setObjectName(_fromUtf8("spinBox_misalignment_x_to"))
        self.gridLayout.addWidget(self.spinBox_misalignment_x_to, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 3, 1, 1)
        self.spinBox_misalignment_y_from = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_misalignment_y_from.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_misalignment_y_from.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_misalignment_y_from.setMinimum(-99)
        self.spinBox_misalignment_y_from.setObjectName(_fromUtf8("spinBox_misalignment_y_from"))
        self.gridLayout.addWidget(self.spinBox_misalignment_y_from, 2, 0, 1, 1)
        self.spinBox_misalignment_y_to = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_misalignment_y_to.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_misalignment_y_to.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_misalignment_y_to.setMinimum(-99)
        self.spinBox_misalignment_y_to.setObjectName(_fromUtf8("spinBox_misalignment_y_to"))
        self.gridLayout.addWidget(self.spinBox_misalignment_y_to, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 3, 1, 1)
        self.spinBox_misalignment_z_from = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_misalignment_z_from.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_misalignment_z_from.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_misalignment_z_from.setMinimum(-99)
        self.spinBox_misalignment_z_from.setObjectName(_fromUtf8("spinBox_misalignment_z_from"))
        self.gridLayout.addWidget(self.spinBox_misalignment_z_from, 3, 0, 1, 1)
        self.spinBox_misalignment_z_to = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_misalignment_z_to.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_misalignment_z_to.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_misalignment_z_to.setMinimum(-99)
        self.spinBox_misalignment_z_to.setObjectName(_fromUtf8("spinBox_misalignment_z_to"))
        self.gridLayout.addWidget(self.spinBox_misalignment_z_to, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 3, 1, 1)
        self.spinBox_z_level_from = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_z_level_from.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_z_level_from.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBox_z_level_from.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_z_level_from.setMinimum(-99)
        self.spinBox_z_level_from.setObjectName(_fromUtf8("spinBox_z_level_from"))
        self.gridLayout.addWidget(self.spinBox_z_level_from, 4, 0, 1, 1)
        self.spinBox_z_level_to = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_z_level_to.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_z_level_to.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_z_level_to.setMinimum(-99)
        self.spinBox_z_level_to.setObjectName(_fromUtf8("spinBox_z_level_to"))
        self.gridLayout.addWidget(self.spinBox_z_level_to, 4, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_3)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 4, 3, 1, 1)
        self.spinBox_misalignment_x_intervall = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_misalignment_x_intervall.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_misalignment_x_intervall.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_misalignment_x_intervall.setMinimum(-99)
        self.spinBox_misalignment_x_intervall.setProperty(_fromUtf8("value"), 1)
        self.spinBox_misalignment_x_intervall.setObjectName(_fromUtf8("spinBox_misalignment_x_intervall"))
        self.gridLayout.addWidget(self.spinBox_misalignment_x_intervall, 1, 2, 1, 1)
        self.spinBox_misalignment_y_intervall = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_misalignment_y_intervall.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_misalignment_y_intervall.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_misalignment_y_intervall.setMinimum(-99)
        self.spinBox_misalignment_y_intervall.setProperty(_fromUtf8("value"), 1)
        self.spinBox_misalignment_y_intervall.setObjectName(_fromUtf8("spinBox_misalignment_y_intervall"))
        self.gridLayout.addWidget(self.spinBox_misalignment_y_intervall, 2, 2, 1, 1)
        self.spinBox_misalignment_z_intervall = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_misalignment_z_intervall.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_misalignment_z_intervall.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_misalignment_z_intervall.setMinimum(-99)
        self.spinBox_misalignment_z_intervall.setProperty(_fromUtf8("value"), 1)
        self.spinBox_misalignment_z_intervall.setObjectName(_fromUtf8("spinBox_misalignment_z_intervall"))
        self.gridLayout.addWidget(self.spinBox_misalignment_z_intervall, 3, 2, 1, 1)
        self.spinBox_z_level_intervall = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_z_level_intervall.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_z_level_intervall.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_z_level_intervall.setMinimum(-99)
        self.spinBox_z_level_intervall.setProperty(_fromUtf8("value"), 1)
        self.spinBox_z_level_intervall.setObjectName(_fromUtf8("spinBox_z_level_intervall"))
        self.gridLayout.addWidget(self.spinBox_z_level_intervall, 4, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(352, 259))
        self.groupBox.setMaximumSize(QtCore.QSize(352, 259))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(13, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 0, 1, 1)
        self.spinBox_young_modulus = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_young_modulus.sizePolicy().hasHeightForWidth())
        self.spinBox_young_modulus.setSizePolicy(sizePolicy)
        self.spinBox_young_modulus.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_young_modulus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_young_modulus.setMaximum(999999.99)
        self.spinBox_young_modulus.setProperty(_fromUtf8("value"), 70000.0)
        self.spinBox_young_modulus.setObjectName(_fromUtf8("spinBox_young_modulus"))
        self.gridLayout_5.addWidget(self.spinBox_young_modulus, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(13, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 0, 1, 1)
        self.spinBox_poisson_ratio = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_poisson_ratio.sizePolicy().hasHeightForWidth())
        self.spinBox_poisson_ratio.setSizePolicy(sizePolicy)
        self.spinBox_poisson_ratio.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_poisson_ratio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_poisson_ratio.setSingleStep(0.1)
        self.spinBox_poisson_ratio.setProperty(_fromUtf8("value"), 0.3)
        self.spinBox_poisson_ratio.setObjectName(_fromUtf8("spinBox_poisson_ratio"))
        self.gridLayout_5.addWidget(self.spinBox_poisson_ratio, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(13, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 2, 0, 1, 1)
        self.spinBox_Plate_Thickness = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Plate_Thickness.sizePolicy().hasHeightForWidth())
        self.spinBox_Plate_Thickness.setSizePolicy(sizePolicy)
        self.spinBox_Plate_Thickness.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_Plate_Thickness.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBox_Plate_Thickness.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_Plate_Thickness.setMaximum(500.0)
        self.spinBox_Plate_Thickness.setProperty(_fromUtf8("value"), 40.0)
        self.spinBox_Plate_Thickness.setObjectName(_fromUtf8("spinBox_Plate_Thickness"))
        self.gridLayout_5.addWidget(self.spinBox_Plate_Thickness, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 2, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.select_L_file = QtGui.QPushButton(self.groupBox)
        self.select_L_file.setObjectName(_fromUtf8("select_L_file"))
        self.gridLayout_3.addWidget(self.select_L_file, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 1, 1, 2)
        self.select_LT_file = QtGui.QPushButton(self.groupBox)
        self.select_LT_file.setObjectName(_fromUtf8("select_LT_file"))
        self.gridLayout_3.addWidget(self.select_LT_file, 0, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 4, 1, 2)
        self.lc1 = QtGui.QDoubleSpinBox(self.groupBox)
        self.lc1.setMinimumSize(QtCore.QSize(80, 0))
        self.lc1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lc1.setDecimals(7)
        self.lc1.setMinimum(-99.999999)
        self.lc1.setMaximum(99.999999)
        self.lc1.setSingleStep(0.1)
        self.lc1.setObjectName(_fromUtf8("lc1"))
        self.gridLayout_3.addWidget(self.lc1, 1, 0, 1, 2)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 2, 1, 1)
        self.ltc1 = QtGui.QDoubleSpinBox(self.groupBox)
        self.ltc1.setMinimumSize(QtCore.QSize(80, 0))
        self.ltc1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ltc1.setDecimals(7)
        self.ltc1.setMinimum(-99.999999)
        self.ltc1.setMaximum(99.999999)
        self.ltc1.setSingleStep(0.1)
        self.ltc1.setObjectName(_fromUtf8("ltc1"))
        self.gridLayout_3.addWidget(self.ltc1, 1, 3, 1, 2)
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 1, 5, 1, 1)
        self.lc2 = QtGui.QDoubleSpinBox(self.groupBox)
        self.lc2.setMinimumSize(QtCore.QSize(80, 0))
        self.lc2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lc2.setDecimals(7)
        self.lc2.setMinimum(-99.999999)
        self.lc2.setMaximum(99.999999)
        self.lc2.setSingleStep(0.1)
        self.lc2.setObjectName(_fromUtf8("lc2"))
        self.gridLayout_3.addWidget(self.lc2, 2, 0, 1, 2)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 2, 2, 1, 1)
        self.ltc2 = QtGui.QDoubleSpinBox(self.groupBox)
        self.ltc2.setMinimumSize(QtCore.QSize(80, 0))
        self.ltc2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ltc2.setDecimals(7)
        self.ltc2.setMinimum(-99.999999)
        self.ltc2.setMaximum(99.999999)
        self.ltc2.setSingleStep(0.1)
        self.ltc2.setObjectName(_fromUtf8("ltc2"))
        self.gridLayout_3.addWidget(self.ltc2, 2, 3, 1, 2)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 2, 5, 1, 1)
        self.lc3 = QtGui.QDoubleSpinBox(self.groupBox)
        self.lc3.setMinimumSize(QtCore.QSize(80, 0))
        self.lc3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lc3.setDecimals(7)
        self.lc3.setMinimum(-99.999999)
        self.lc3.setMaximum(99.999999)
        self.lc3.setSingleStep(0.1)
        self.lc3.setObjectName(_fromUtf8("lc3"))
        self.gridLayout_3.addWidget(self.lc3, 3, 0, 1, 2)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 3, 2, 1, 1)
        self.ltc3 = QtGui.QDoubleSpinBox(self.groupBox)
        self.ltc3.setMinimumSize(QtCore.QSize(80, 0))
        self.ltc3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ltc3.setDecimals(7)
        self.ltc3.setMinimum(-99.999999)
        self.ltc3.setMaximum(99.999999)
        self.ltc3.setSingleStep(0.1)
        self.ltc3.setObjectName(_fromUtf8("ltc3"))
        self.gridLayout_3.addWidget(self.ltc3, 3, 3, 1, 2)
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 3, 5, 1, 1)
        self.lc4 = QtGui.QDoubleSpinBox(self.groupBox)
        self.lc4.setMinimumSize(QtCore.QSize(80, 0))
        self.lc4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lc4.setDecimals(7)
        self.lc4.setMinimum(-99.999999)
        self.lc4.setMaximum(99.999999)
        self.lc4.setSingleStep(0.1)
        self.lc4.setObjectName(_fromUtf8("lc4"))
        self.gridLayout_3.addWidget(self.lc4, 4, 0, 1, 2)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 4, 2, 1, 1)
        self.ltc4 = QtGui.QDoubleSpinBox(self.groupBox)
        self.ltc4.setMinimumSize(QtCore.QSize(80, 0))
        self.ltc4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ltc4.setDecimals(7)
        self.ltc4.setMinimum(-99.999999)
        self.ltc4.setMaximum(99.999999)
        self.ltc4.setSingleStep(0.1)
        self.ltc4.setObjectName(_fromUtf8("ltc4"))
        self.gridLayout_3.addWidget(self.ltc4, 4, 3, 1, 2)
        self.lc5 = QtGui.QDoubleSpinBox(self.groupBox)
        self.lc5.setMinimumSize(QtCore.QSize(80, 0))
        self.lc5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lc5.setDecimals(7)
        self.lc5.setMinimum(-99.999999)
        self.lc5.setMaximum(99.999999)
        self.lc5.setSingleStep(0.1)
        self.lc5.setObjectName(_fromUtf8("lc5"))
        self.gridLayout_3.addWidget(self.lc5, 5, 0, 1, 2)
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 5, 2, 1, 1)
        self.ltc5 = QtGui.QDoubleSpinBox(self.groupBox)
        self.ltc5.setMinimumSize(QtCore.QSize(80, 0))
        self.ltc5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ltc5.setDecimals(7)
        self.ltc5.setMinimum(-99.999999)
        self.ltc5.setMaximum(99.999999)
        self.ltc5.setSingleStep(0.1)
        self.ltc5.setObjectName(_fromUtf8("ltc5"))
        self.gridLayout_3.addWidget(self.ltc5, 5, 3, 1, 2)
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 5, 5, 1, 1)
        self.lc6 = QtGui.QDoubleSpinBox(self.groupBox)
        self.lc6.setMinimumSize(QtCore.QSize(80, 0))
        self.lc6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lc6.setDecimals(7)
        self.lc6.setMinimum(-99.999999)
        self.lc6.setMaximum(99.999999)
        self.lc6.setSingleStep(0.1)
        self.lc6.setObjectName(_fromUtf8("lc6"))
        self.gridLayout_3.addWidget(self.lc6, 6, 0, 1, 2)
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 6, 2, 1, 1)
        self.ltc6 = QtGui.QDoubleSpinBox(self.groupBox)
        self.ltc6.setMinimumSize(QtCore.QSize(80, 0))
        self.ltc6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ltc6.setDecimals(7)
        self.ltc6.setMinimum(-99.999999)
        self.ltc6.setMaximum(99.999999)
        self.ltc6.setSingleStep(0.1)
        self.ltc6.setObjectName(_fromUtf8("ltc6"))
        self.gridLayout_3.addWidget(self.ltc6, 6, 3, 1, 2)
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 6, 5, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 4, 5, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setMinimumSize(QtCore.QSize(0, 152))
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_4.addWidget(self.label_21, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 0, 1, 2, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.button_select_output = QtGui.QPushButton(dialog)
        self.button_select_output.setObjectName(_fromUtf8("button_select_output"))
        self.verticalLayout.addWidget(self.button_select_output)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.line_2 = QtGui.QFrame(dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.button_select_file = QtGui.QPushButton(dialog)
        self.button_select_file.setObjectName(_fromUtf8("button_select_file"))
        self.verticalLayout.addWidget(self.button_select_file)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.gridLayout_8.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.JobTable = QtGui.QTableWidget(dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JobTable.sizePolicy().hasHeightForWidth())
        self.JobTable.setSizePolicy(sizePolicy)
        self.JobTable.setMinimumSize(QtCore.QSize(640, 120))
        self.JobTable.setMaximumSize(QtCore.QSize(640, 16777215))
        self.JobTable.setRowCount(0)
        self.JobTable.setColumnCount(29)
        self.JobTable.setObjectName(_fromUtf8("JobTable"))
        self.JobTable.setColumnCount(29)
        self.JobTable.setRowCount(0)
        self.gridLayout_8.addWidget(self.JobTable, 2, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.button_add_to_table = QtGui.QPushButton(dialog)
        self.button_add_to_table.setEnabled(False)
        self.button_add_to_table.setObjectName(_fromUtf8("button_add_to_table"))
        self.horizontalLayout.addWidget(self.button_add_to_table)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.button_start_calculation = QtGui.QPushButton(dialog)
        self.button_start_calculation.setEnabled(False)
        self.button_start_calculation.setObjectName(_fromUtf8("button_start_calculation"))
        self.horizontalLayout.addWidget(self.button_start_calculation)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.button_dialog = QtGui.QDialogButtonBox(dialog)
        self.button_dialog.setOrientation(QtCore.Qt.Horizontal)
        self.button_dialog.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.button_dialog.setObjectName(_fromUtf8("button_dialog"))
        self.horizontalLayout.addWidget(self.button_dialog)
        self.gridLayout_8.addLayout(self.horizontalLayout, 3, 0, 1, 2)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)
        dialog.setTabOrder(self.button_select_file, self.spinBox_misalignment_x_from)
        dialog.setTabOrder(self.spinBox_misalignment_x_from, self.spinBox_misalignment_y_from)
        dialog.setTabOrder(self.spinBox_misalignment_y_from, self.spinBox_misalignment_z_from)
        dialog.setTabOrder(self.spinBox_misalignment_z_from, self.spinBox_young_modulus)
        dialog.setTabOrder(self.spinBox_young_modulus, self.spinBox_poisson_ratio)
        dialog.setTabOrder(self.spinBox_poisson_ratio, self.spinBox_Plate_Thickness)
        dialog.setTabOrder(self.spinBox_Plate_Thickness, self.lc1)
        dialog.setTabOrder(self.lc1, self.lc2)
        dialog.setTabOrder(self.lc2, self.lc3)
        dialog.setTabOrder(self.lc3, self.lc4)
        dialog.setTabOrder(self.lc4, self.lc5)
        dialog.setTabOrder(self.lc5, self.lc6)
        dialog.setTabOrder(self.lc6, self.ltc1)
        dialog.setTabOrder(self.ltc1, self.ltc2)
        dialog.setTabOrder(self.ltc2, self.ltc3)
        dialog.setTabOrder(self.ltc3, self.ltc4)
        dialog.setTabOrder(self.ltc4, self.ltc5)
        dialog.setTabOrder(self.ltc5, self.ltc6)
        dialog.setTabOrder(self.ltc6, self.button_add_to_table)
        dialog.setTabOrder(self.button_add_to_table, self.button_start_calculation)
        dialog.setTabOrder(self.button_start_calculation, self.JobTable)

    def retranslateUi(self, dialog):
        dialog.setWindowTitle(QtGui.QApplication.translate("dialog", "Machining Distortion Prediction", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("dialog", "Set User Defined Misalignment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("dialog", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("dialog", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("dialog", "Intervall", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dialog", "Angle X-Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dialog", "Angle Y-Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("dialog", "Angle Z-Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("dialog", "Z-Level", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("dialog", "Material Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("dialog", "Young Modulus", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("dialog", "Poisson Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("dialog", "Plate Thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.select_L_file.setText(QtGui.QApplication.translate("dialog", "Select L File", None, QtGui.QApplication.UnicodeUTF8))
        self.select_LT_file.setText(QtGui.QApplication.translate("dialog", "Select LT File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("dialog", "LC1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("dialog", "LTC1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("dialog", "LC2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("dialog", "LTC2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("dialog", "LC3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("dialog", "LTC3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("dialog", "LC4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("dialog", "LC5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("dialog", "LTC5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("dialog", "LC6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("dialog", "LTC6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("dialog", "LTC4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("dialog", "Interpolation Coefficients", None, QtGui.QApplication.UnicodeUTF8))
        self.button_select_output.setText(QtGui.QApplication.translate("dialog", "Select Overall Output Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.button_select_file.setText(QtGui.QApplication.translate("dialog", "Select Nastran Geometry File", None, QtGui.QApplication.UnicodeUTF8))
        self.button_add_to_table.setText(QtGui.QApplication.translate("dialog", "Add Job", None, QtGui.QApplication.UnicodeUTF8))
        self.button_start_calculation.setText(QtGui.QApplication.translate("dialog", "Start Calculation", None, QtGui.QApplication.UnicodeUTF8))

