#if !defined( PYCXX_STANDARD_EXCEPTION )
#pragma error( "define PYCXX_STANDARD_EXCEPTION before including" )
#endif

PYCXX_STANDARD_EXCEPTION( LookupError,          StandardError )
PYCXX_STANDARD_EXCEPTION( ArithmeticError,      StandardError )
PYCXX_STANDARD_EXCEPTION( EnvironmentError,     StandardError )
PYCXX_STANDARD_EXCEPTION( TypeError,            StandardError )
PYCXX_STANDARD_EXCEPTION( IndexError,           LookupError )
PYCXX_STANDARD_EXCEPTION( AttributeError,       StandardError )
PYCXX_STANDARD_EXCEPTION( NameError,            StandardError )
PYCXX_STANDARD_EXCEPTION( RuntimeError,         StandardError )
PYCXX_STANDARD_EXCEPTION( NotImplementedError,  StandardError )
PYCXX_STANDARD_EXCEPTION( SystemError,          StandardError )
PYCXX_STANDARD_EXCEPTION( KeyError,             LookupError )
PYCXX_STANDARD_EXCEPTION( ValueError,           StandardError )
PYCXX_STANDARD_EXCEPTION( OverflowError,        ArithmeticError )
PYCXX_STANDARD_EXCEPTION( ZeroDivisionError,    ArithmeticError )
PYCXX_STANDARD_EXCEPTION( FloatingPointError,   ArithmeticError )
PYCXX_STANDARD_EXCEPTION( MemoryError,          StandardError )
PYCXX_STANDARD_EXCEPTION( SystemExit,           StandardError )
