# gitlab CI config file

# this image is on dockerhub. Dockerfile is here: https://gitlab.com/PrzemoF/FreeCAD/-/blob/gitlab-v1/ci/Dockerfile
image: freecadci/runner

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

before_script:
  - apt-get update -yqq
  # CCache Config
  - mkdir -p ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/ccache

cache:
  paths:
    - ccache/

build-job:       # This job runs in the build stage, which runs first.
  stage: build

  script:
    - echo "Compiling the code..."
    - mkdir build
    - cd build
    - ccache cmake ../
    - ccache cmake --build ./ -j$(nproc)
    - echo "Compile complete."

  artifacts:
    paths:
     - build/

test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... "
    - cd build/bin/
    # Testing currently doesn't work due to problems with libraries ot being visible by the binary.
    - ./FreeCADCmd -t 0

