macro(SetupLibPRC)
    # -------------------------------- libPRC --------------------------------
    if(BUILD_PDF_EXPORT_3D)
        if(FREECAD_USE_EXTERNAL_LIBPRC)
            find_package(libPRC REQUIRED)
        else()
            # Using bundled libPRC
            set(libPRC_FOUND TRUE)
            set(libPRC_INCLUDE_DIRS ${CMAKE_SOURCE_DIR}/src/3rdParty/libPRC/src/libPRC)
            if(PRC_USE_ASYMPTOTE)
                set(libPRC_LIBRARIES asymptote)
            else()
                set(libPRC_LIBRARIES libPRC)
            endif()
        endif()
        
        if(libPRC_FOUND)
            message(STATUS "Found libPRC")
        else()
            message(FATAL_ERROR "libPRC not found")
        endif()
    else()
        message(STATUS "PDF export disabled, skipping libPRC setup")
    endif()
endmacro(SetupLibPRC) 