macro(SetupParser)
    find_package(BISON)
    find_package(FLEX)

    set(PARSER_TOOLS_FOUND False)
    if(BISON_FOUND)
        message(STATUS "Found Bison ${BISON_VERSION}")
        if(FLEX_FOUND)
            message(STATUS "Found Flex ${FLEX_VERSION}")
            set(PARSER_TOOLS_FOUND True)
        endif()
    endif()
endmacro()

function(spdx_clang_format_copy IN_FILE OUT_FILE)
    file(WRITE ${OUT_FILE} "// SPDX-License-Identifier: LGPL-2.1-or-later\n\n")
    file(APPEND ${OUT_FILE} "// clang-format off\n")
    file(READ ${IN_FILE} CONTENTS)
    file(APPEND ${OUT_FILE} "${CONTENTS}")
endfunction()

if(COPY_PARSER_FILES)
    string(REPLACE "\"" "" DEST_PARSER_DIR ${DEST_PARSER_DIR})
    string(REPLACE "\"" "" COPY_PARSER_FILES ${COPY_PARSER_FILES})
    string(REPLACE " " ";" COPY_PARSER_FILES ${COPY_PARSER_FILES})
    foreach(arg IN ITEMS ${COPY_PARSER_FILES})
        spdx_clang_format_copy("${CMAKE_CURRENT_BINARY_DIR}/${arg}" "${DEST_PARSER_DIR}/${arg}")
    endforeach()
endif()
