del bin\assistant.exe
del bin\Coin4d.dll
del bin\designer.exe
del bin\freetyped.dll
del bin\libcrypto-3d.dll
del bin\libEGLd.dll
del bin\libGLESv2d.dll
del bin\linguist.exe
del bin\qdoc.exe
del bin\Qt53DAnimationd.dll
del bin\Qt53DCored.dll
del bin\Qt53DExtrasd.dll
del bin\Qt53DInputd.dll
del bin\Qt53DLogicd.dll
del bin\Qt53DQuickAnimationd.dll
del bin\Qt53DQuickd.dll
del bin\Qt53DQuickExtrasd.dll
del bin\Qt53DQuickInputd.dll
del bin\Qt53DQuickRenderd.dll
del bin\Qt53DQuickScene2Dd.dll
del bin\Qt53DRenderd.dll
del bin\Qt5Bluetoothd.dll
del bin\Qt5Bodymovind.dll
del bin\Qt5Chartsd.dll
del bin\Qt5Concurrentd.dll
del bin\Qt5Cored.dll
del bin\Qt5DataVisualizationd.dll
del bin\Qt5DBusd.dll
del bin\Qt5DesignerComponentsd.dll
del bin\Qt5Designerd.dll
del bin\Qt5Gamepadd.dll
del bin\Qt5Guid.dll
del bin\Qt5Helpd.dll
del bin\Qt5Locationd.dll
del bin\Qt5Multimediad.dll
del bin\Qt5MultimediaQuickd.dll
del bin\Qt5MultimediaWidgetsd.dll
del bin\Qt5NetworkAuthd.dll
del bin\Qt5Networkd.dll
del bin\Qt5Nfcd.dll
del bin\Qt5OpenGLd.dll
del bin\Qt5Pdfd.dll
del bin\Qt5PdfWidgetsd.dll
del bin\Qt5Positioningd.dll
del bin\Qt5PositioningQuickd.dll
del bin\Qt5PrintSupportd.dll
del bin\Qt5Purchasingd.dll
del bin\Qt5Qmld.dll
del bin\Qt5QmlModelsd.dll
del bin\Qt5QmlWorkerScriptd.dll
del bin\Qt5Quick3DAssetImportd.dll
del bin\Qt5Quick3Dd.dll
del bin\Qt5Quick3DRenderd.dll
del bin\Qt5Quick3DRuntimeRenderd.dll
del bin\Qt5Quick3DUtilsd.dll
del bin\Qt5QuickControls2d.dll
del bin\Qt5Quickd.dll
del bin\Qt5QuickParticlesd.dll
del bin\Qt5QuickShapesd.dll
del bin\Qt5QuickTemplates2d.dll
del bin\Qt5QuickTestd.dll
del bin\Qt5QuickWidgetsd.dll
del bin\Qt5RemoteObjectsd.dll
del bin\Qt5Scriptd.dll
del bin\Qt5ScriptToolsd.dll
del bin\Qt5Scxmld.dll
del bin\Qt5Sensorsd.dll
del bin\Qt5SerialBusd.dll
del bin\Qt5SerialPortd.dll
del bin\Qt5Sqld.dll
del bin\Qt5Svgd.dll
del bin\Qt5Testd.dll
del bin\Qt5TextToSpeechd.dll
del bin\Qt5VirtualKeyboardd.dll
del bin\Qt5WebChanneld.dll
del bin\Qt5WebEngineCored.dll
del bin\Qt5WebEngined.dll
del bin\Qt5WebEngineWidgetsd.dll
del bin\Qt5WebSocketsd.dll
del bin\Qt5WebViewd.dll
del bin\Qt5Widgetsd.dll
del bin\Qt5WinExtrasd.dll
del bin\Qt5Xmld.dll
del bin\Qt5XmlPatternsd.dll
del bin\QtWebEngineProcessd.exe
del bin\Quarter1d.dll
del bin\xerces-c_3_2D.dll
del bin\zlibd.dll
