c_compiler:               # [win]
  - vs2022                # [win]
cxx_compiler:             # [win]
  - vs2022                # [win]

c_stdlib_version:         # [osx and x86_64]
  - "10.13"               # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET: # [osx and x86_64]
  - "10.13"               # [osx and x86_64]
