[workspace]
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "win-64"]
preview = ["pixi-build"]

[package]
name = "parashell"
version = "1.2.0dev"
homepage = "https://www.parashell.cloud"
repository = "https://www.parashell.cloud/open-source"
description = "Parashell"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[feature.freecad.dependencies]
freecad = { path = "." }
flask = "*"
sentry-sdk = "*"
pyjwt = "*"

[feature.freecad.target.linux-64.dependencies]
uvloop = "*"

[feature.freecad.target.linux-aarch64.dependencies]
uvloop = "*"

[feature.freecad.target.osx-arm64.dependencies]
uvloop = "*"

[feature.freecad.target.win-64.dependencies]
ucrt = "==10.0.20348.0"
winloop = "*"

[feature.package.dependencies]
python = ">=3.11,<3.12"

[feature.package.tasks]
create_bundle = 'bash -c "cd $(bash scripts/get_os.bash) && bash create_bundle.sh"'

## Linux (x86-64)
[feature.package.target.linux-64.dependencies]
coreutils = "*"
xcb-util-cursor = ">=0.1.6,<0.2.0a0"

## Linux (aarch64)
[feature.package.target.linux-aarch64.dependencies]
coreutils = "*"
xcb-util-cursor = ">=0.1.6,<0.2.0a0"

## macOS (Apple Silicon)
[feature.package.target.osx-arm64.dependencies]
coreutils = "*"
dmgbuild = "*"
pyobjc-framework-Quartz = "*"
sed = "*"

## Windows dependencies (x86-64)
[feature.package.target.win-64.dependencies]
git = "*"
nsis = { version = "*", build = "*_log*" }
7zip = "*"
ucrt = "==10.0.20348.0"
vs2022_win-64 = "*"

[environments]
default = ["freecad"]
package = ["package"]