#ifndef FREECAD_BOOST_PYTHON_HPP_WORKAROUND
#define FREECAD_BOOST_PYTHON_HPP_WORKAROUND

// Workaround for boost >= 1.74
#define BOOST_ALLOW_DEPRECATED_HEADERS
#include <boost/python.hpp>
#undef BOOST_ALLOW_DEPRECATED_HEADERS

#endif // #ifndef FREECAD_BOOST_PYTHON_HPP_WORKAROUND
