#!/bin/bash
# This script has translatable strings. Extract them using:
# bash --dump-po-strings AppRun > AppRun.pot
set -eu

HERE="$(dirname "$(readlink -f "${0}")")"
export PREFIX="${HERE}/usr"

# Do not export these variables!
TEXTDOMAIN="AppRun"
TEXTDOMAINDIR="${HERE}/locale"

requirements_not_met() {
    TITLE=$"FreeCAD launch error"
    NOTMET=$"FreeCAD cannot run because the following requirements are not met:"
    TEXT="${NOTMET}"$'\n'"${1}"
    echo "${TEXT}" >&2
    if [ -n "${DISPLAY:-}" ] || [ -n "${WAYLAND_DISPLAY:-}" ]; then
        if command -v zenity >/dev/null 2>&1; then
            zenity --error --text="${TEXT}" --title="${TITLE}" --icon-name="${HERE}/launch-error.svg"
        elif command -v yad >/dev/null 2>&1; then
            yad --text="${TEXT}" --title="${TITLE}" --image="${HERE}/launch-error.svg" --escape-ok
        elif command -v kdialog >/dev/null 2>&1; then
            kdialog --error "${TEXT}" --title "${TITLE}"
        elif command -v notify-send >/dev/null 2>&1; then
            notify-send -u normal -a FreeCAD -n "${HERE}/org.freecad.FreeCAD.svg" -i "${HERE}/launch-error.svg" "${TITLE}" "${TEXT}"
        elif command -v gxmessage >/dev/null 2>&1; then
            gxmessage "${TEXT}"
        elif command -v xmessage >/dev/null 2>&1; then
            xmessage "${TEXT}"
        fi
    fi
    exit 127
}

# Check for CPU architecture version. x86 Conda has started requiring x86-64-v2:
# https://www.anaconda.com/blog/updated-cpu-requirements-linux-recommendations-windows
ARCH="$(uname -m)"
if [ "${ARCH}" = x86_64 ]; then
    # x86-64 architecture level detection from https://unix.stackexchange.com/a/631226
    ARCHVER="$(awk -f- <<'EOF'
BEGIN {
    while (!/flags/) if (getline < "/proc/cpuinfo" != 1) exit 1
    if (/lm/&&/cmov/&&/cx8/&&/fpu/&&/fxsr/&&/mmx/&&/syscall/&&/sse2/) level = 1
    if (level == 1 && /cx16/&&/lahf/&&/popcnt/&&/sse4_1/&&/sse4_2/&&/ssse3/) level = 2
    if (level == 2 && /avx/&&/avx2/&&/bmi1/&&/bmi2/&&/f16c/&&/fma/&&/abm/&&/movbe/&&/xsave/) level = 3
    if (level == 3 && /avx512f/&&/avx512bw/&&/avx512cd/&&/avx512dq/&&/avx512vl/) level = 4
    print level
    exit 0
}
EOF
)"
    MIN_ARCHVER=2
    if [ "${ARCHVER}" -lt "${MIN_ARCHVER}" ]; then
        requirements_not_met $"Your computer's processor is too old (x86_64-v${ARCHVER}, minimum required is x86_64-v${MIN_ARCHVER})."
    fi
fi

# export LD_LIBRARY_PATH="${HERE}/usr/lib${LD_LIBRARY_PATH:+':'}$LD_LIBRARY_PATH"
export PYTHONHOME="${HERE}/usr"
export PATH_TO_FREECAD_LIBDIR="${HERE}/usr/lib"
# export QT_QPA_PLATFORM_PLUGIN_PATH="${HERE}/usr/plugins"
export FONTCONFIG_FILE=/etc/fonts/fonts.conf
export FONTCONFIG_PATH=/etc/fonts

# Use X by default even on Wayland, but allow overriding via FREECAD_QT_QPA_PLATFORM.
# Warn users of this if QT_QPA_PLATFORM is already set by their environment.
if [ -z "${FREECAD_QT_QPA_PLATFORM:-}" ] && [ -n "${QT_QPA_PLATFORM:-}" ]; then
    echo "Warning: \$QT_QPA_PLATFORM has no effect on FreeCAD AppImages. Use \$FREECAD_QT_QPA_PLATFORM instead." >&2
fi
export QT_QPA_PLATFORM="${FREECAD_QT_QPA_PLATFORM:-xcb}"

# Use XDG Desktop Portals by default. Qt gracefully falls back to whichever platform
# theme it detected should be next in the chain (gtk3 or Qt built-in) if an XDG
# portal implementation isn't reachable over D-Bus.
export QT_QPA_PLATFORMTHEME="${QT_QPA_PLATFORMTHEME:-xdgdesktopportal}"

# Set the XKBCommon config location here, as this path (or a host-side path) isn't
# automatically picked up when starting with a Wayland QT_QPA_PLATFORM.
export XKB_CONFIG_EXTRA_PATH="${XKB_CONFIG_EXTRA_PATH:-${PREFIX}/share/xkeyboard-config-2}"

# Set the XCursor paths if they're otherwise unset to fix https://github.com/FreeCAD/FreeCAD/issues/26726
# which resurfaced as xcb-util-cursor 0.1.6 now picks up its default path from its build environment,
# a thing Conda packagers did not pick up on and so the library now ships with build placeholder paths
# included. Those obviously lead to nowhere on any user system, and causes fallbacks to antiquated X11 cursors.
export XCURSOR_PATH="${XCURSOR_PATH:-~/.local/share/icons:~/.icons:/usr/share/icons:/usr/share/pixmaps:${PREFIX}/share/icons:${PREFIX}/share/pixmaps}"

# Show packages info if DEBUG env variable is set
if [ "${DEBUG:-}" = 1 ]; then
    cat "${HERE}/packages.txt"
fi

# SSL
# https://forum.freecad.org/viewtopic.php?f=4&t=34873&start=20#p327416
export SSL_CERT_FILE="${PREFIX}/ssl/cacert.pem"
# https://github.com/FreeCAD/FreeCAD-AppImage/pull/20
export GIT_SSL_CAINFO="${HERE}/usr/ssl/cacert.pem"

# Support for launching other applications (from /usr/bin)
# https://github.com/FreeCAD/FreeCAD-AppImage/issues/30
if [ ! -z "${1:-}" ] && [ -e "${HERE}/usr/bin/$1" ] ; then
    MAIN="${HERE}/usr/bin/${1}" ; shift
else
    MAIN="${HERE}/usr/bin/freecad"
fi

exec "${MAIN}" "$@"
