name: Backport merged pull request

on:
  pull_request_target:
    types: [closed, labeled]
    branches: [main, releases/*]

permissions:
  contents: read

jobs:
  backport:
    name: Create backport pull request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    # Run the action if a PR is merged with backport labels
    # OR
    # when already merged PR is labeled with backport labels
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
        || (
          github.event.action == 'labeled'
          && startsWith(github.event.label.name, 'backport ')
        )
      )
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          egress-policy: audit

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.BACKPORT_CLIENT_ID }}
          private-key: ${{ secrets.BACKPORT_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ github.event.pull_request.base.repo.full_name }}
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Create backport pull requests
        uses: korthout/backport-action@8560fb503c275d433c56f05a2f64850093baa9f7 # v4.7.0
        with:
          # Inputs documented here: https://github.com/korthout/backport-action?tab=readme-ov-file#inputs
          github_token: ${{ steps.app-token.outputs.token }}
          github_workspace: ${{ github.workspace }}

          # permit PRs with merge commits to be backported
          merge_commits: 'skip'

          # copy labels to backport to identify affected systems and priorities
          copy_labels_pattern: '.*'

          # Regex pattern to match github labels
          # The capture group catches the target branch
          # i.e. label "backport releases/FreeCAD-1-0" will create backport
          # PR for branch releases/FreeCAD-1-0
          label_pattern: ^backport ([^ ]+)$
