# .github/workflows/caller.yml
name: Caller Workflow

on:
  push:  # Or any other trigger event (e.g., pull_request)
  workflow_dispatch: # allows manual triggering with inputs. Needed for local testing.

jobs:
  call_lint:
    uses: ./.github/workflows/sub_buildWindows.yml  # Replace with the path to your Lint workflow file. The ./ refers to the project root
    with:
      artifactBasename: "test-artifact"  # Provide values for required inputs
      changedFiles: "file1.txt file2.cpp"
      changedCppFiles: "file2.cpp"
      changedPythonFiles: "file3.py"
      checkLineendings: true # Provide default values for other inputs
      checkWhitespace: true
      checkTabs: true
      checkQtConnections: true
      checkCpplint: true
      cpplintFilters: ''
      cpplintLineLength: '120'
      cpplintFailSilent: true
      checkPylint: true
      pylintDisable: 'C0302,C0303'
      pylintFailSilent: true
      checkBlack: true
      blackFailSilent: true
      checkClangFormat: false
      clangStyle: 'file'
      clangFormatFailSilent: true
      checkSpelling: true
      listIgnoredMisspelling: '.github/codespellignore'
      spellingIgnore: './.git,*.po,*.ts,*.svg,./ChangeLog.txt,./src/3rdParty,./src/Mod/Assembly/App/opendcm,./src/CXX,./src/zipios++,./src/Base/swig*,./src/Mod/Robot/App/kdl_cp,./src/Mod/Import/App/SCL*,./src/WindowsInstaller,./src/Doc/FreeCAD.uml,./build/'
      codespellFailSilent: true
      checkClangTidy: true
      clangTidyFailSilent: true
      checkClazy: true
      clazyChecks: 'level2,no-non-pod-global-static,no-copyable-polymorphic'
      clazyFailSilent: true
      checkClazyQT6: true
      clazyQT6Checks: 'qt6-deprecated-api-fixes,qt6-header-fixes,qt6-qhash-signature,qt6-fwd-fixes,missing-qobject-macro'
      QT6Branch: 'main'
      clazyQT6FailSilent: true
