name: Semgrep
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '21 14 * * 6'
permissions:
  contents: read
jobs:
  semgrep:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: semgrep ci --sarif-output=semgrep.sarif || true
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SECURITY_CI_SEMGREP_APP_TOKEN }}
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
        if: always() && hashFiles('semgrep.sarif') != ''
